// German translations; keys are the English UI copy.
export const german: Record<string, string> = {
  "Preparing": "Vorbereitung",
  "Checking albums": "Alben prüfen",
  "Device assignments complete": "Gerätezuordnung fertig",
  "Immich returned HTTP {status}. Check the URL, API key, and permissions.": "Immich antwortet mit HTTP {status}. Prüfe URL, API-Key und Berechtigungen.",
  "Immich denied {permission} ({operation}).": "Immich verweigert {permission} ({operation}).",
  "Assets": "Assets",
  "Administrator": "Admin",
  "Export": "Export",
  "captures. Click to view assets.": "Aufnahmen. Klicken für Assets.",
  "Average photo resolution by capture year in megapixels": "Durchschnittliche Fotoauflösung je Aufnahmejahr in Megapixel",
  "Schematic fields of view for the five most frequent original EXIF focal lengths": "Schematische Bildwinkel-Kegel der fünf häufigsten originalen EXIF-Brennweiten",
  "Library timeline": "Chronik der Bibliothek",
  "{year}: average {mp} megapixels across {count} photos": "{year}: durchschnittlich {mp} Megapixel bei {count} Fotos",
  "{year}: view values": "{year}: Werte anzeigen",
  "Captures by device: {metric}": "Aufnahmen nach Gerät: {metric}",
  "percent": "Prozent",
  "Frequency distribution of {name}": "Häufigkeitsverteilung {name}",
  "{year}: view captures": "{year}: Aufnahmen anzeigen",
  "Average MB per file by capture year": "Durchschnittliche MB je Datei nach Aufnahmejahr",
  "Cumulative media by capture year": "Kumulative Medien nach Aufnahmejahr",
  "Portrait format": "Hochformat",
  "cumulative": "cumulative",
  "dark": "dark",
  "device": "device",
  "hour": "hour",
  "landscape": "landscape",
  "logarithmic scale": "log",
  "media": "media",
  "month": "month",
  "photos": "photos",
  "portrait": "portrait",
  "year": "year",
  "assets": "assets",
  "Library": "Bibliothek",
  "Year highlights": "Jahres-Highlights",
  "Date range": "Zeitraum",
  "Photo profile": "Fotoprofil",
  "Download": "Download",
  "Profile": "Profil",
  "Your photo library,": "Deine Fotobibliothek,",
  "at a glance.": "auf einen Blick.",
  "in total": "insgesamt",
  "Newest photo": "Neuestes Foto",
  "Avg. per asset": "Ø pro Asset",
  "Avg. per photo": "Ø pro Foto",
  "Avg. per video": "Ø pro Video",
  "Sign out": "Abmelden",
  "Member": "Mitglied",
  "Your account": "Dein Konto",
  "Display name": "Anzeigename",
  "Profile icon": "Profil-Icon",
  "Save profile": "Profil speichern",
  "Private to you": "Nur für dich",
  "Immich connection": "Immich-Verbindung",
  "No API key saved": "Kein API-Key hinterlegt",
  "API key saved": "API-Key hinterlegt",
  "No Immich URL saved yet": "Noch keine Immich-URL gespeichert",
  "New API key": "Neuer API-Key",
  "Save connection": "Verbindung speichern",
  "Test connection": "Verbindung prüfen",
  "Replace API key": "Neuen API-Key hinterlegen",
  "Cancel": "Abbrechen",
  "Security": "Sicherheit",
  "Change password": "Passwort ändern",
  "Current password": "Aktuelles Passwort",
  "New password": "Neues Passwort",
  "Administration": "Verwaltung",
  "Invite a member": "Person einladen",
  "Create invitation link": "Einladungslink erstellen",
  "Share link": "Link weitergeben",
  "Copy": "Kopieren",
  "Invited": "Eingeladen",
  "New link": "Neuer Link",
  "Delete": "Löschen",
  "Permanently delete member": "Mitglied endgültig löschen",
  "To confirm, type": "Zur Bestätigung",
  "Data export": "Datenexport",
  "Your library": "Deine Bibliothek",
  "Your date range": "Dein Zeitraum",
  "Your photo profile": "Dein Fotoprofil",
  "Download your data": "Deine Daten herunterladen",
  "Entire library": "Gesamte Bibliothek",
  "A year of memories": "Ein Jahr voller Erinnerungen",
  "Year": "Jahr",
  "From": "Von",
  "To": "Bis",
  "Refresh now": "Jetzt aktualisieren",
  "Overview": "Überblick",
  "Evolution": "Entwicklung",
  "Unknown device": "Unbekanntes Gerät",
  "Unknown manufacturer": "Unbekannter Hersteller",
  "Your media": "Deine Medien",
  "total assets": "Assets insgesamt",
  "Favorites": "Favoriten",
  "Your albums": "Eigene Alben",
  "Assets without album": "Assets ohne Album",
  "Original files": "Originaldateien",
  "Storage": "Speicher",
  "Total storage": "Speicher gesamt",
  "Photo storage": "Fotos belegen",
  "Video storage": "Videos belegen",
  "Image formats": "Bildformate",
  "Which image dimensions occur?": "Welche Bildabmessungen kommen vor?",
  "Metadata": "Metadaten",
  "People": "Menschen",
  "Places": "Orte",
  "Time span": "Zeitspanne",
  "From the beginning to today": "Von Anfang bis heute",
  "Cameras & devices": "Kameras & Geräte",
  "What was it shot with?": "Womit aufgenommen?",
  "Correct devices": "Geräte korrigieren",
  "No device information available.": "Keine Geräteinformationen verfügbar.",
  "Exposure settings distribution": "Verteilung der Aufnahmeparameter",
  "Focal length comparison": "Brennweitenvergleich",
  "Your five most common angles of view": "Deine fünf häufigsten Bildwinkel",
  "Time of day": "Tageszeit",
  "Month": "Monat",
  "Photos": "Fotos",
  "Videos": "Videos",
  "All devices": "Alle Geräte",
  "Camera": "Kamera",
  "Mobile device": "Mobilgerät",
  "Other": "Sonstiges",
  "With location": "Mit Standort",
  "With person": "Mit Person",
  "Linear": "Linear",
  "Logarithmic": "Logarithmisch",
  "Scale": "Skala",
  "Open profile": "Profil öffnen",
  "Device": "Gerät",
  "Exposure time": "Belichtungszeit",
  "Video length": "Videolänge",
  "Your five most frequent original focal lengths": "Deine fünf häufigsten originalen Brennweiten",
  "Loading focal lengths from stored EXIF values…": "Brennweiten werden aus gespeicherten EXIF-Werten geladen …",
  "Focal lengths are taken unchanged from each photo’s focalLength. Click a bar to see those exact assets. The device filter only reads the stored snapshot.": "Die Brennweiten stammen unverändert aus focalLength der einzelnen Bilder. Balken anklicken, um genau diese Assets zu sehen. Der Gerätefilter liest nur den gespeicherten Datenstand.",
  "Use Immich profile photo": "Immich-Profilbild verwenden",
  "Choose your Immich profile photo or an app icon. The Immich photo requires the optional avatar permission.": "Wähle dein Immich-Profilbild oder eines der App-Icons. Das Immich-Bild benötigt die optionale Avatar-Berechtigung.",
  "Checking connection…": "Verbindung wird geprüft …",
  "Last checked": "Zuletzt geprüft",
  "Checking…": "Prüfe …",
  "Immich is reachable. Only your own assets are counted.": "Immich ist erreichbar. Es werden nur deine eigenen Assets gezählt.",
  "Volumes by year": "Mengen nach Jahr",
  "How are your captures distributed?": "Wie verteilen sich deine Aufnahmen?",
  "Total": "Gesamt",
  "Average per capture year": "Durchschnitt je Aufnahmejahr",
  "Captures by year": "Aufnahmen nach Jahr",
  "Assets with a person": "Assets mit Person",
  "Assets with location": "Assets mit Standort",
  "of the total": "des Gesamtwerts",
  "Click to view matching assets": "Klicken: passende Assets anzeigen",
  "Technique & time": "Technik & Zeit",
  "For perspective": "Zum Vorstellen",
  "Your library in numbers": "Deine Bibliothek in Zahlen",
  "Captures": "Aufnahmen",
  "Average photo resolution": "Ø Auflösung der Fotos",
  "Most common ISO": "Häufigster ISO-Wert",
  "Most common focal length": "Häufigste Brennweite",
  "Most common shutter speed": "Häufigste Verschlusszeit",
  "Total video duration": "Videolaufzeit gesamt",
  "Average video length": "Ø Videolänge",
  "Cumulative exposure time": "Kumulierte Verschlusszeit",
  "Photos with people": "Fotos mit Personen",
  "Categorized people": "Kategorisierte Personen",
  "Total detected people": "Insgesamt detektierte Menschen",
  "Avg. people per photo with people": "Ø Personen pro Foto mit Personen",
  "Avg. people per photo overall": "Ø Personen pro Foto insgesamt",
  "Assets with location data": "Assets mit Standortdaten",
  "Countries with location data": "Länder mit Standortdaten",
  "Continents with location data": "Kontinente mit Standortdaten",
  "Africa": "Afrika",
  "Antarctica": "Antarktika",
  "Asia": "Asien",
  "Europe": "Europa",
  "North America": "Nordamerika",
  "South America": "Südamerika",
  "Oceania": "Ozeanien",
  "File size": "Dateigröße",
  "Original size unknown": "Originalgröße unbekannt",
  "First capture": "Erste Aufnahme",
  "Last capture": "Letzte Aufnahme",
  "Busiest day": "Tag mit den meisten Assets",
  "Days with photos": "Tage mit Fotos",
  "Longest break": "Längste Pause",
  "Longest daily streak": "Längster Tagesstreak",
  "Longest weekly streak": "Längster Wochenstreak",
  "Portrait and landscape": "Hochkant und Querformat",
  "Portrait": "Hochkant",
  "Landscape": "Querformat",
  "Unknown / square": "Nicht bestimmbar / quadratisch",
  "Image quality over time": "Bildqualität über die Zeit",
  "Photo resolution by capture year": "Fotoauflösung nach Aufnahmejahr",
  "EXIF over time": "EXIF im Zeitverlauf",
  "Exposure settings by year": "Aufnahmeparameter nach Jahr",
  "Captures per year & year-over-year change": "Aufnahmen pro Jahr & Veränderung zum Vorjahr",
  "Device development": "Geräteentwicklung",
  "Which devices shaped your years?": "Welche Geräte prägen deine Jahre?",
  "Annual contribution": "Jährlicher Beitrag",
  "Who contributed to the year?": "Wer hat zum neuen Jahr beigetragen?",
  "Your tendencies": "Deine Tendenzen",
  "Between two poles · by year": "Zwischen zwei Polen · nach Jahren",
  "Tendency score": "Tendenzwert",
  "Area comparison": "Flächenvergleich",
  "Manufacturers and devices": "Hersteller und Geräte",
  "Donut chart": "Donut-Diagramm",
  "When do you capture your media?": "Wann entstehen deine Medien?",
  "{hour} · {count} captures": "{hour} Uhr · {count} Aufnahmen",
  "Name and profile image are saved automatically. The Immich photo requires the optional avatar permission.": "Name und Profilbild werden automatisch gespeichert. Das Immich-Bild benötigt die optionale Avatar-Berechtigung.",
  "When?": "Wann?",
  "By month": "Nach Monat",
  "By weekday": "Nach Wochentag",
  "By hour": "Nach Tagesstunde",
  "{hour} · {count} assets": "{hour} Uhr · {count} Assets",
  "{focal} mm: view {count} photos": "{focal} mm: {count} Fotos ansehen",
  "EXIF by time of day and month": "EXIF im Tages- und Jahresrhythmus",
  "Aperture": "Blende",
  "Back to statistics": "Zurück zu den Statistiken",
  "Assets in stored snapshot": "Assets im gespeicherten Datenstand",
  "Matching media": "Passende Medien",
  "Searching matching assets in the local cache…": "Passende Assets werden im lokalen Cache gesucht …",
  "No assets are stored for this filter.": "Für diesen Filter sind keine Assets gespeichert.",
  "Load 36 more": "Weitere 36 laden",
  "Loading…": "Lade …",
  "Capture date unknown": "Aufnahmedatum unbekannt",
  "Thumbnails are loaded from Immich on demand. The selection and counts come from your stored profile snapshot.": "Vorschaubilder werden bei Bedarf aus Immich geladen. Die Auswahl und Anzahl stammen aus deinem gespeicherten Profil-Datenstand.",
  "Enable light mode": "Hellmodus einschalten",
  "Enable dark mode": "Dunkelmodus einschalten",
  "Light": "Hell",
  "Dark": "Dunkel",
  "required": "erforderlich",
  "optional": "optional",
  "Read owned assets and their EXIF, people, and location data": "Eigene Assets und ihre EXIF-, Personen- und Standortdaten lesen",
  "Read Immich user ID to exclude shared assets": "Immich-Benutzer-ID zum Ausschluss geteilter Assets lesen",
  "Load missing file sizes and verify thumbnails": "Fehlende Dateigrößen nachladen und Vorschaubilder absichern",
  "Display a thumbnail of your latest photo": "Vorschaubild des neuesten eigenen Fotos anzeigen",
  "Adopt Immich profile photo": "Immich-Profilbild übernehmen",
  "Count owned albums": "Eigene Alben zählen",
  "Total binary digits": "0/1-Stellen insgesamt",
  "As grains of sand": "Als Sandkörner",
  "All photos as 10 × 15 cm prints": "Alle Fotos als 10 × 15 cm Abzüge",
  "Height of the print stack": "Höhe als Fotostapel",
  "Weight of all prints": "Gewicht aller Abzüge",
  "Capture year": "Aufnahmejahr",
  "Years": "Jahre",
  "Days": "Tage",
  "capture month": "Aufnahmemonat",
  "Cumulative by": "Kumulativ nach",
  "Average by": "Durchschnitt pro",
  "MB per file": "MB je Datei",
  "of": "der",
  "Invitees set their own password. You cannot see their libraries or API keys.": "Eingeladene setzen ihr Passwort selbst. Du siehst ihre Bibliotheken und API-Keys nicht.",
  "This link is shown only now and expires in 7 days.": "Der Link wird nur jetzt angezeigt und läuft nach 7 Tagen ab.",
  "permanently delete?": "dauerhaft löschen?",
  "enter": "eingeben",
  "Sessions, API key, cache, statistics, and device corrections for this account are deleted from the database. Immich originals are untouched.": "Sitzungen, API-Key, Cache, Statistiken und Gerätekorrekturen dieses Kontos werden aus der Datenbank entfernt. Immich-Originale bleiben unangetastet.",
  "Your timeline": "Deine Chronik",
  "Notable moments on a timeline": "Besondere Momente auf einem Zeitstrahl",
  "From the first photo to device changes, records, and milestones. Everything follows the capture date in Immich.": "Vom ersten Foto bis zu Gerätewechseln, Rekorden und Meilensteinen. Alles folgt dem Aufnahmedatum in Immich.",
  "Category": "Kategorie",
  "All events": "Alle Ereignisse",
  "Search": "Suche",
  "Device or event": "Gerät oder Ereignis",
  "Control timeline": "Zeitstrahl steuern",
  "Zoom out": "Verkleinern",
  "Zoom in": "Vergrößern",
  "Everything": "Alles",
  "Recent": "Jüngste",
  "First & last": "Erste & letzte",
  "Devices": "Geräte",
  "Milestones": "Meilensteine",
  "Records": "Rekorde",
  "Breaks": "Pausen",
  "View matching assets": "Passende Assets ansehen",
  "Gramps Web open-source project": "Open-Source-Projekt Gramps Web",
  "Many thanks to its team for their excellent work!": "Vielen Dank an das Team für seine großartige Arbeit!",
  "Use the mouse wheel to zoom and drag to pan. Colors mark event types; click grouped points repeatedly to cycle through them.": "Mausrad zum Zoomen, ziehen zum Verschieben. Farben kennzeichnen Ereignisarten; gebündelte Punkte lassen sich mehrfach anklicken.",
  "Use the mouse wheel to zoom and drag to pan. Click a point or label to view matching assets.": "Mausrad zum Zoomen, ziehen zum Verschieben. Punkt oder Beschriftung anklicken, um die passenden Assets zu sehen.",
  "events in view": "Ereignisse im Ausschnitt",
  "No events for this selection.": "Keine Ereignisse für diese Auswahl.",
  "Timeline: mouse wheel zooms, drag or swipe pans, arrow keys navigate": "Zeitstrahl: Mausrad vergrößert; ziehen oder wischen verschiebt; Pfeiltasten navigieren",
  "ISO, focal length & aperture by {axis}": "ISO, Brennweite & Blende nach {axis}",
  "Appearance & language": "Darstellung & Sprache",
  "Accent color": "Akzentfarbe",
  "Green": "Grün",
  "Purple": "Lila",
  "Blue": "Blau",
  "Amber": "Bernstein",
  "Chart palette": "Diagramm-Farbpalette",
  "Balanced": "Ausgewogen",
  "Vivid": "Kräftig",
  "Calm": "Ruhig",
  "Aurora": "Polarlicht",
  "Colorblind-friendly": "Farbenblind-freundlich",
  "Language": "Sprache",
  "Immich API key permissions": "Berechtigungen für den Immich-API-Key",
  "Grant these permissions when creating the key in Immich. The list is based on the backend API calls.": "Wähle beim Erstellen des Schlüssels in Immich diese Rechte aus. Die Liste wird vom Backend aus den verwendeten API-Aufrufen erzeugt.",
  "Albums created by you": "Von dir angelegte Alben",
  "Albums with at least one asset in this period": "Alben mit mindestens einem Asset im Zeitraum",
  "Album membership unavailable": "Albumzuordnung nicht verfügbar",
  "{photos} photos · {videos} videos": "{photos} Fotos · {videos} Videos",
  "Original files according to Immich": "Originaldateien laut Immich",
  "{count} file sizes missing": "{count} Dateigrößen fehlen",
  "Others": "Andere",
  "Photo": "Foto",
  "Video": "Video",
  "ISO, focal length & aperture by time of day": "ISO, Brennweite & Blende nach Tageszeit",
  "ISO, focal length & aperture by month": "ISO, Brennweite & Blende nach Monat",
  "Number of bits in the original files": "Anzahl Bits in den Originaldateien",
  "Illustrative time comparison": "Illustrativer Zeitvergleich",
  "1 bit = 1 grain (Ø 0.25 mm, 64% packing)": "1 Bit = 1 Korn (Ø 0,25 mm, 64 % Packung)",
  "0.2 mm per 10 × 15 cm print": "0,2 mm je 10 × 15 cm Abzug",
  "2 g per 10 × 15 cm print": "2 g je 10 × 15 cm Abzug",
  "Estimate at 7 cents per 10 × 15 cm print, excluding shipping": "Schätzung mit 7 Cent pro 10 × 15 cm Abzug, ohne Versand",
  "Priceless": "Unbezahlbar",
  "with known resolution": "mit Auflösung",
  "{count} photos with exactly this value": "{count} Fotos mit genau diesem Wert",
  "{count} standalone videos with known duration": "{count} eigenständige Videos mit Laufzeit",
  "{count} photos with shutter speed": "{count} Fotos mit Verschlusszeit",
  "All image formats": "Alle Bildformate",
  "Very large formats are fitted for display only; their aspect ratio stays unchanged.": "Sehr große Formate werden nur für die Darstellung eingepasst; ihr Seitenverhältnis bleibt unverändert.",
  "Minimum per format": "Mindestanzahl je Format",
  "No image format reaches this minimum.": "Kein Bildformat erreicht diese Mindestanzahl.",
  "{visible} of {total} image formats shown · {matches} matching photos. Set the minimum to 1 to show every format matching the filter.": "{visible} von {total} Bildformaten sichtbar · {matches} passende Fotos. Mindestanzahl 1 zeigt alle zum Filter passenden Formate.",
  "{covered} of {photos} photos have stored dimensions.": "{covered} von {photos} Fotos haben gespeicherte Bildabmessungen.",
  "{count} videos without duration": "{count} Videos ohne Laufzeit",
  "Only standalone videos with known duration": "Nur eigenständige Videos mit Laufzeit",
  "{count} photos without shutter speed": "{count} Fotos ohne Verschlusszeit",
  "Person associations across all assets": "Personenzuordnungen über alle Assets",
  "Most common: {country} ({count} assets)": "Am häufigsten: {country} ({count} Assets)",
  "Days with photos {year}": "Tage mit Fotos {year}",
  "{count} days": "{count} Tage",
  "{count} weeks": "{count} Wochen",
  "{percent}% of {count} calendar days": "{percent} % von {count} Kalendertagen",
  " · first to last capture": " · erste bis letzte Aufnahme",
  "{count} assets without capture date": "{count} Assets ohne Aufnahmedatum",
  "{start} to {end}": "{start} bis {end}",
  "Snapshot: {date}": "Datenstand: {date}",
  "No snapshot saved yet.": "Noch kein gespeicherter Datenstand.",
  "Immich is syncing in the background. The previous snapshot remains available.": "Immich wird im Hintergrund abgeglichen. Der bisherige Stand bleibt verfügbar.",
  "A database sync can take a long time for a large library. You can continue using the page; the previous snapshot remains available until the new one is complete.": "Der Datenbank-Abgleich kann bei einer großen Bibliothek gut und gern sehr lange dauern. Du kannst die Seite in der Zwischenzeit weiter benutzen; der bisherige Datenstand bleibt erhalten, bis der neue vollständig ist.",
  "Stored snapshot": "Der gespeicherte Datenstand",
  "Connect your Immich account first.": "Verbinde zuerst dein Immich-Konto.",
  "Save your Immich URL and personal API key in your profile.": "Hinterlege deine Immich-URL und deinen persönlichen API-Key im Profil.",
  "Go to profile": "Zum Profil",
  "The SQLite file contains cached assets, statistics, album IDs, and your device corrections. PDF, CSV, and JPG are compact reports. Passwords, API keys, and original images are excluded from every export.": "Die SQLite-Datei enthält gecachte Assets, Statistiken, Album-IDs und deine Geräte-Korrekturen. PDF, CSV und JPG sind kompakte Statistikberichte. Passwörter, API-Keys und Originalbilder sind in keinem Export enthalten.",
  "Refresh the library first.": "Bitte zuerst die Bibliothek aktualisieren.",
  "Choose start and end dates.": "Wähle Start und Ende.",
  "Both start and end dates are included.": "Die Tage am Anfang und Ende zählen mit.",
  "Initial sync in progress…": "Erster Abgleich läuft …",
  "Scan the library once": "Bibliothek einmal einlesen",
  "Use “Refresh now” to start the background sync.": "Mit „Jetzt aktualisieren“ startest du den Hintergrundabgleich.",
  "Calculating library statistics…": "Bibliothek wird ausgewertet …",
  "This can take a moment for large libraries.": "Bei großen Bibliotheken kann das einen Moment dauern.",
  "{name} and the stored account data were deleted.": "{name} und die gespeicherten Kontodaten wurden gelöscht.",
  "Largest photo by file size": "Speicherlastigstes Foto",
  "Largest video by file size": "Speicherlastigstes Video",
  "largest known original file of this media type.": "größte bekannte Originaldatei dieser Medienart.",
  "Value": "Wert",
  "Y axis": "Y-Achse",
  "Standard deviation": "Standardabweichung",
  "All photos": "Alle Fotos",
  "No dated photos with EXIF data are available for this value and filter.": "Für diesen Wert und Filter liegen keine datierten Fotos mit EXIF-Daten vor.",
  "Line = arithmetic mean of photos with this EXIF value; gray band = ±1 population standard deviation. Missing values and undated photos are excluded.": "Linie = arithmetischer Mittelwert aus Fotos mit diesem EXIF-Wert; graue Spanne = ±1 Populations-Standardabweichung. Fehlende Werte und undatierte Fotos zählen nicht.",
  "Click a year to view matching photos from that period.": "Jahresbereich anklicken, um passende Fotos des Zeitabschnitts zu sehen.",
  "Capture year {year}": "Aufnahmejahr {year}",
  "Device type": "Geräteart",
  "Color landscape and portrait separately": "Quer- und Hochformat farblich unterscheiden",
  "Centered image format frames colored by frequency": "Bildformate als zentrierte, nach Häufigkeit eingefärbte Rahmen",
  "Shared center; gray means no match for the filter. All {formats} stored formats are shown, covering {covered} of {photos} photos.": "Gemeinsamer Mittelpunkt; grau bedeutet keinen Treffer für den Filter. Alle {formats} gespeicherten Formate sichtbar; sie decken {covered} von {photos} Fotos ab.",
  "Logarithmic color scale.": "Logarithmische Farbskala.",
  "Linear color scale.": "Lineare Farbskala.",
  "Most common image dimensions": "Häufigste Bildabmessungen",
  "Hover or select a frame; click to view matching photos.": "Rahmen berühren oder auswählen; klicken für die passenden Fotos.",
  "Square": "Quadratisch",
  "Your stored snapshot": "Dein gespeicherter Datenstand",
  "SQLite database": "SQLite-Datenbank",
  "Calculating size once…": "Größe wird einmalig ermittelt …",
  "Size unavailable": "Größe nicht verfügbar",
  "Download SQLite": "SQLite herunterladen",
  "Calculating size…": "Größe wird ermittelt …",
  "Selection": "Auswahl",
  "Manufacturer": "Hersteller",
  "All": "Alle",
  "Manufacturer · grouped": "Hersteller · zusammengefasst",
  "Manufacturer · individual": "Hersteller · einzeln",
  "Color mode": "Farbmodus",
  "Count": "Anzahl",
  "Mobile device ↔ camera": "Mobilgerät ↔ Kamera",
  "Portrait ↔ landscape": "Hochkant ↔ Querformat",
  "Photo ↔ video": "Foto ↔ Video",
  "Activity only": "Nur Aktivität",
  "Anniversaries": "Jahrestage",
  "Year overview": "Jahresübersicht",
  "Library over time": "Bibliothek im Zeitverlauf",
  "On which day of the year do you capture media?": "An welchem Jahrestag entstehen deine Medien?",
  "Capture calendar {year}": "Aufnahmekalender {year}",
  "Your entire library by week": "Deine gesamte Bibliothek nach Wochen",
  "all capture years": "alle Aufnahmejahre",
  "to": "bis",
  "Empty · portrait · tie · landscape": "Leer · Hochkant · Gleichstand · Querformat",
  "Empty · photo · tie · video": "Leer · Foto · Gleichstand · Video",
  "Empty · mobile device · tie · camera": "Leer · Mobilgerät · Gleichstand · Kamera",
  "Unassigned": "Keine Zuordnung",
  "Tie": "Gleichstand",
  "Accent color = at least one capture": "Akzentfarbe = mindestens eine Aufnahme",
  "{max} · {scale} · strongest color = maximum": "{max} · {scale} · kräftigste Farbe = Höchstwert",
  "linear": "linear",
  "logarithmic": "logarithmisch",
  "Values summed over all capture years; February 29 remains a separate day.": "Werte über alle Aufnahmejahre summiert; der 29. Februar bleibt ein eigener Tag.",
  "Monday to Sunday; exactly one cell per day.": "Montag bis Sonntag; jeder Tag genau ein Feld.",
  "Rhythm": "Rhythmus",
  "Hours of a typical week": "Stunden einer typischen Woche",
  "All capture years in the selected period combined; each cell counts media captured in that weekday-hour.": "Alle Aufnahmejahre des gewählten Zeitraums zusammengefasst; jede Kachel zählt Medien in dieser Wochentags-Stunde.",
  "{width} × {height} pixels: {count} photos in the selection": "{width} × {height} Pixel: {count} Fotos für die Auswahl",
  "{width} × {height} pixels · {count} in the selection": "{width} × {height} Pixel · {count} in der Auswahl",
  "{selected} captures in the selection · {total} photos overall": "{selected} Aufnahmen in der Auswahl · {total} Fotos insgesamt",
  "{value} by {axis}": "{value} nach {axis}",
  "hour of day": "Tagesstunde",
  "{hour}:00": "{hour} Uhr",
  "{bucket}: view {count} matching photos": "{bucket}: {count} passende Fotos ansehen",
  "Sync in progress": "Abgleich läuft",
  "Full sync": "Vollständiger Abgleich",
  "Fast incremental sync": "Schneller Folgeabgleich",
  "Loading assets": "Assets laden",
  "Checking assets": "Assets prüfen",
  "Loading changes": "Änderungen laden",
  "Checking assets without albums": "Ohne Album prüfen",
  "Calculating statistics": "Statistiken berechnen",
  "Updating database": "Datenbank aktualisieren",
  "Calculating device assignments": "Gerätezuordnung lokal berechnen",
  "Calculating local statistics": "Statistiken lokal berechnen",
  "No changes": "Keine Änderungen",
  "Done": "Fertig",
  "Failed": "Fehlgeschlagen",
  "Metadata is missing for this distribution.": "Für diese Verteilung fehlen Metadaten.",
  "Individual values": "Einzelwerte",
  "second": "Sekunde",
  "seconds": "Sekunden",
  "exposure stops": "Blendenstufen",
  "X axis": "X-Achse",
  "Labels": "Beschriftung",
  "1/… seconds": "1/… Sekunden",
  "Decimal seconds": "Dezimal-Sekunden",
  "Typical range (up to 99%)": "Typischer Bereich (bis 99 %)",
  "Minimum captures per bar": "Mindestens Aufnahmen je Balken",
  "Resolution": "Auflösung",
  "No bar reaches the minimum frequency.": "Kein Balken erreicht die Mindesthäufigkeit.",
  "Median": "Median",
  "Mean": "Mittelwert",
  "Most frequent exact value": "Häufigster Einzelwert",
  "Smallest": "Kleinste",
  "Largest": "Größte",
  "ISO value": "ISO-Wert",
  "{count} captures with a value · The darker bar marks the most frequent displayed range; the accent line marks the most frequent exact value.": "{count} Aufnahmen mit Wert · Der dunklere Balken markiert den häufigsten angezeigten Bereich, die Akzentlinie den häufigsten exakten Einzelwert.",
  "{bins} rare ranges with {assets} captures hidden.": "{bins} seltene Bereiche mit {assets} Aufnahmen ausgeblendet.",
  "The most frequent exact value lies outside the visible ranges.": "Der häufigste Einzelwert liegt außerhalb der sichtbaren Bereiche.",
  "Median, mean, and most frequent exact value still include all values.": "Median, Mittelwert und häufigster Einzelwert beziehen sich weiterhin auf alle Werte.",
  "{count} with known resolution": "{count} mit Auflösung",
  "Your selected range": "Dein gewählter Ausschnitt",
  "1 bit = 1 second": "1 Bit = 1 Sekunde",
  "Cost of all photo prints": "Preis aller Fotoabzüge",
  "Value of your memories": "Wert deiner Erinnerungen",
  "Mobile device (phone/tablet/iPod)": "Mobilgerät (Smartphone/Tablet/iPod)",
  "Other / unknown": "Sonstiges / unbekannt",
  "Separate names": "Namen trennen",
  "Merge names": "Namen zusammenfassen",
  "No captures for this filter.": "Keine Aufnahmen für diesen Filter.",
  "Place": "Platz",
  "Models": "Modelle",
  "EXIF names": "EXIF-Namen",
  "Which EXIF manufacturer names were merged?": "Welche EXIF-Herstellerbezeichnungen wurden zusammengefasst?",
  "No image dimensions are available for these years.": "Für diese Jahre liegen keine Bildabmessungen vor.",
  "Show minimum and maximum": "Minimum und Maximum zeigen",
  "Photo resolution": "Fotoauflösung",
  "Minimum": "Minimum",
  "Maximum": "Maximum",
  "photos with dimensions": "Fotos mit Abmessungen",
  "Average": "Durchschnitt",
  "By capture year, only photos with known dimensions. Minimum and maximum can be influenced by unusual image formats.": "Je Aufnahmejahr, nur Fotos mit bekannten Abmessungen. Minimum und Maximum können durch einzelne ungewöhnliche Bildformate geprägt sein.",
  "No original EXIF focal lengths available yet.": "Noch keine originalen EXIF-Brennweiten verfügbar.",
  "Diagonal angle of view · schematic reach": "Diagonaler Bildwinkel · schematische Reichweite",
  "diagonal": "diagonal",
  "Top 5 by original EXIF focal length. To compare different cameras and calculate their actual angles of view, a 35 mm-equivalent focal length or sensor dimensions are needed. The plotted angles use a schematic full-frame reference; cone length is not subject distance. See Profile → Notes.": "Top 5 nach originaler EXIF-Brennweite. Um verschiedene Kameras und ihre tatsächlichen Bildwinkel zu vergleichen, braucht man die 35-mm-äquivalente Brennweite oder die Sensorabmessungen. Die gezeigten Winkel sind nur eine schematische Vollformat-Referenz; die Kegellänge ist keine Motivdistanz. Mehr dazu unter Profil → Hinweise.",
  "Inspired by the": "Inspiriert vom",
  "Correct device assignments": "Gerätezuordnung korrigieren",
  "Immich Insights automatically classifies devices using EXIF manufacturer and model. Here you can rename combinations for your profile, assign a manufacturer, and classify them as camera, mobile device, or other. Original EXIF data remains unchanged.": "Immich Insights ordnet Geräte automatisch anhand von EXIF-Hersteller und Modell zu. Hier kannst du einzelne Kombinationen für dein Profil umbenennen, einem Hersteller zuordnen und als Kamera, Mobilgerät oder Sonstiges einstufen. Originale EXIF-Daten bleiben unverändert.",
  "Your devices appear here after the first sync.": "Nach dem ersten Abgleich erscheinen hier deine Geräte.",
  "Search devices": "Gerät suchen",
  "Manufacturer or model": "Hersteller oder Modell",
  "Corrected": "Korrigiert",
  "Automatic": "Automatisch",
  " · corrected": " · korrigiert",
  "No matching devices.": "Keine passenden Geräte.",
  "Current assignment": "Aktuelle Zuordnung",
  "Device category": "Gerätekategorie",
  "Save correction": "Korrektur speichern",
  "Reset": "Zurücksetzen",
  "Choose a device on the left.": "Wähle links ein Gerät aus.",
  "Saved. Statistics are recalculated locally without a new Immich scan.": "Gespeichert. Die Statistiken werden lokal neu berechnet – ohne neuen Immich-Scan.",
  "Correction removed. Automatic classification is restored locally.": "Korrektur entfernt. Die automatische Zuordnung wird lokal wiederhergestellt.",
  "Photo days & rhythm": "Fototage & Rhythmus",
  "Your activity in numbers": "Deine Aktivität in Zahlen",
  "Avg. photos per photo day": "Ø Fotos pro Fototag",
  "Avg. streak length": "Ø Streak-Länge",
  "Avg. break between photo days": "Ø Pause zwischen Fototagen",
  "Avg. activity cycle": "Ø Aktivitätszyklus",
  "Avg. photos/day in streaks": "Ø Fotos/Tag in Streaks",
  "Maximum on a streak day": "Maximum an einem Streak-Tag",
  "Streak vs. normal photo day": "Streak vs. normaler Fototag",
  "Photo days in ≥3-day streaks": "Fototage in ≥3-Tage-Streaks",
  "A photo day has at least one photo. A streak contains at least two consecutive photo days; a break counts only complete photo-free days between activity phases. A cycle includes an activity phase, even a single day, followed by its break.": "Fototag = mindestens ein Foto. Ein Streak umfasst mindestens zwei aufeinanderfolgende Fototage; eine Pause zählt nur vollständige Tage ohne Foto zwischen zwei Aktivitätsphasen. Der Zyklus umfasst eine Aktivitätsphase einschließlich Einzeltagen plus ihre folgende Pause.",
  "Distributions": "Verteilungen",
  "How long do streaks and breaks last?": "Wie lang dauern Serien und Pausen?",
  "Streak lengths": "Streak-Längen",
  "Streak days": "Streak-Tage",
  "Break days": "Pausentage",
  "No completed multi-day streaks yet.": "Noch keine abgeschlossenen mehrtägigen Streaks.",
  "No completed breaks yet.": "Noch keine abgeschlossenen Pausen.",
  "Number of phases": "Anzahl der Phasen",
  "After a streak": "Nach einer Serie",
  "Intensity and following break": "Intensität und folgende Pause",
  "Do more photos per streak day lead to a longer break?": "Je mehr Fotos pro Streak-Tag, desto länger die Pause danach?",
  "Completed streaks with a following break are needed for comparison.": "Für einen Vergleich fehlen abgeschlossene Streaks mit anschließender Pause.",
  "Photos/day in a streak → avg. break days; streaks of at least two days": "Fotos/Tag im Streak → Ø Pausentage; nur Streaks ab zwei Tagen",
  "Pearson correlation": "Pearson-Korrelation",
  "−1: more intense streaks, shorter breaks · 0: no linear relation · +1: longer breaks. Requires at least three evaluable streak-break pairs.": "−1: intensivere Streaks, kürzere Pausen · 0: kein linearer Zusammenhang · +1: längere Pausen. Nur mit mindestens drei auswertbaren Streak-Pause-Paaren.",
  "Seven indices": "Sieben Indizes",
  "How do you photograph?": "Wie fotografierst du?",
  "Indices describe patterns, not photographic quality. When there are too few photo days or breaks, “—” appears instead of an invented value.": "Indizes beschreiben Muster, keine fotografische Qualität. Bei zu wenigen Fototagen oder Pausen erscheint „—“ statt eines erfundenen Werts.",
  "Over the years": "Über die Jahre",
  "How does your photo profile change?": "Wie verändert sich dein Fotoprofil?",
  "Regularity": "Regelmäßigkeit",
  "Streaks ↔ breaks ↔ stability": "Streaks ↔ Pausen ↔ Stabilität",
  "Avg. streak": "Ø Streak",
  "Avg. break": "Ø Pause",
  "Stability index": "Stabilitätsindex",
  "Stability compares average multi-day streak length with average break length. A high value does not automatically mean more or better photos.": "Die Stabilität setzt die mittlere Länge mehrtägiger Streaks ins Verhältnis zur mittleren Pause. Ein hoher Wert bedeutet nicht automatisch mehr Fotos oder bessere Bilder.",
  "The annual comparison appears once at least two capture years are available.": "Der Jahresvergleich erscheint, sobald mindestens zwei Aufnahmejahre vorliegen.",
  "Annual trend of selected photo profile indices": "Jährlicher Verlauf der ausgewählten Fotoprofil-Indizes",
  "Calculated separately for each calendar year. Streaks and breaks are split at year boundaries.": "Je Kalenderjahr separat berechnet. Streaks und Pausen werden an der Jahresgrenze getrennt.",
  "Focus index": "Fokus-Index",
  "Volatility index": "Volatilitäts-Index",
  "Habit strength index": "Habit-Strength-Index",
  "Rhythm regularity index": "Rhythm-Regularity-Index",
  "Momentum index": "Momentum-Index",
  "Burnout index": "Burnout-Index",
  "Share of all photos captured on the most active rounded-up 10% of photo days.": "Anteil aller Fotos an den aktivsten aufgerundeten 10 % der Fototage.",
  "Variation in photos per photo day: 100 × coefficient of variation / (1 + coefficient of variation).": "Schwankung der Fotos je Fototag: 100 × Variationskoeffizient / (1 + Variationskoeffizient).",
  "Share of photo days belonging to a streak of at least three days.": "Anteil der Fototage, die zu einer Folge von mindestens drei Tagen gehören.",
  "100 / (1 + coefficient of variation of intervals between photo days). At least three photo days required.": "100 / (1 + Variationskoeffizient der Abstände zwischen Fototagen). Mindestens drei Fototage nötig.",
  "Average photos on first streak days / (average first days + average later streak days) × 100. A score of 50 means equal intensity.": "Mittlere Fotozahl am ersten Streak-Tag / (Mittel erster Tage + Mittel der weiteren Streak-Tage) × 100. 50 bedeutet gleich intensive Tage.",
  "Average break after ≥3-day streaks / (that break + overall average break) × 100. A score of 50 means equally long breaks.": "Mittlere Pause nach ≥3-Tage-Streaks / (diese Pause + mittlere Pause insgesamt) × 100. 50 bedeutet gleich lange Pausen.",
  "Average streak length / (average streak length + average break) × 100.": "Mittlere Streak-Länge / (mittlere Streak-Länge + mittlere Pause) × 100.",
  "Between two poles": "Zwischen zwei Polen",
  "The marker shows your tendency. The exact method is listed under “Calculation”. This is not a rating.": "Der Punkt zeigt deine Tendenz. Die genaue Berechnung steht jeweils unter „Berechnung“. Das ist keine Bewertung.",
  "Your photo personality appears once enough matching metadata is available.": "Deine Bildpersönlichkeit wird sichtbar, sobald genug passende Metadaten vorliegen.",
  "Labeled radar chart of six tendencies": "Beschriftetes Spinnennetz der sechs Tendenzen",
  "Undetermined": "Nicht bestimmbar",
  "undetermined": "nicht bestimmbar",
  "Leaning toward {pole}": "Eher {pole}",
  "Evenly balanced": "Ausgeglichen",
  "{percent}% toward {pole}": "{percent} % Richtung {pole}",
  "{eligible} of {total} {kind} eligible": "{eligible} von {total} {kind} auswertbar",
  " · {count} excluded": " · {count} ausgeschlossen",
  "Calculation": "Berechnung",
  "Connections in the radar chart are missing when individual tendencies cannot be determined.": "Im Spinnennetz fehlen Verbindungen, wenn einzelne Tendenzen nicht bestimmbar sind.",
  "Media": "Medien",
  "Daylight": "Taglicht",
  "Night": "Nacht",
  "ISO / light": "ISO / Licht",
  "Bright light": "Helles Licht",
  "Low light": "Low-Light",
  "Capture frequency": "Aufnahmefrequenz",
  "Frequency": "Frequenz",
  "Single shot": "Einzelschuss",
  "Burst mode": "Dauerfeuer",
  "Orientation": "Bildformat",
  "Capture device": "Aufnahmegerät",
  "Media mix": "Medienmix",
  "08:00–18:00: 0 · 06:00–08:00 & 18:00–22:00: 0.5 · 22:00–06:00: 1": "08–18 Uhr: 0 · 06–08 & 18–22 Uhr: 0,5 · 22–06 Uhr: 1",
  "Up to ISO 400: 0 · 800–1600: 0.5 · ISO 3200+: 1; linear in between.": "Bis ISO 400: 0 · 800–1600: 0,5 · ab 3200: 1; dazwischen linear.",
  "Time since the previous photo: up to 5 s = 1 · 10 min or more = 0; linear in between.": "Abstand zum vorherigen Foto: bis 5 s = 1 · ab 10 min = 0; dazwischen linear.",
  "Landscape: 0 · square: 0.5 · portrait: 1.": "Querformat: 0 · quadratisch: 0,5 · Hochformat: 1.",
  "Camera: 0 · phone/tablet/iPod: 1 · other excluded.": "Kamera: 0 · Smartphone/Tablet/iPod: 1 · Sonstiges ausgeschlossen.",
  "Photos: 0 · videos: 1. The score is the video share of all photos and videos.": "Fotos: 0 · Videos: 1. Der Wert ist der Videoanteil aller Fotos und Videos.",
  "Film architect": "Filmarchitekt",
  "You like telling stories in moving images.": "Du erzählst gern in bewegten Bildern.",
  "Moment keeper": "Momentenbewahrer",
  "One moment can carry your stories.": "Ein einzelner Augenblick trägt deine Geschichten.",
  "Night chronicler": "Nachtchronist",
  "Your subjects begin where daylight ends.": "Deine Motive beginnen, wenn das Tageslicht endet.",
  "Light collector": "Lichtsammler",
  "You make use of daylight clarity.": "Du nutzt die Klarheit des Tages.",
  "Low-light seeker": "Dunkellichtsucher",
  "Challenging light does not stop you.": "Auch schwieriges Licht hält dich nicht auf.",
  "Moment hunter": "Augenblickjäger",
  "You capture fast action in bursts.": "Du hältst schnelle Abläufe in Serien fest.",
  "Portrait storyteller": "Hochkant-Erzähler",
  "You often frame scenes vertically.": "Dein Blick denkt oft in vertikalen Szenen.",
  "Wide-frame thinker": "Panoramadenker",
  "You give your subjects room across the frame.": "Du lässt deinen Motiven Raum in der Breite.",
  "Pocket reporter": "Taschenreporter",
  "Your camera is always with you.": "Die Kamera ist immer dabei.",
  "Camera artist": "Kamerakünstler",
  "You often reach for a dedicated camera.": "Du greifst gern zur eigenen Kamera.",
  "No dated photos or videos are available for an annual trend.": "Keine datierten Fotos oder Videos für einen Jahresverlauf vorhanden.",
  "Choose a tendency. Each point represents a capture year; gaps indicate years without matching captures.": "Wähle eine Tendenz. Jeder Punkt steht für ein Aufnahmejahr; Lücken bedeuten Jahre ohne passende Aufnahmen.",
  "Choose one or more tendencies. Each point represents a capture year; gaps indicate years without matching captures.": "Wähle eine oder mehrere Tendenzen. Jeder Punkt steht für ein Aufnahmejahr; Lücken bedeuten Jahre ohne passende Aufnahmen.",
  "Annual trend of selected tendencies": "Jährlicher Verlauf der ausgewählten Tendenzen",
  "Annual trend": "Jahresverlauf",
  "Annual tendency between {low} and {high}": "Jährliche Tendenz zwischen {low} und {high}",
  "Capture year {year}: {tendency}": "Aufnahmejahr {year}: {tendency}",
  "The middle means balanced. The right pole is at the top, the left at the bottom. Capture frequency only compares photos within the same year.": "Die Mitte steht für ein ausgeglichenes Verhältnis. Oben liegt der rechte Pol, unten der linke. Bei der Aufnahmefrequenz zählt nur der Abstand zu Fotos desselben Jahres.",
  "The middle means balanced. Each metric’s second pole is at the top and first pole at the bottom. Capture frequency only compares photos within the same year.": "Die Mitte steht für ein ausgeglichenes Verhältnis. Oben liegt jeweils der zweite, unten der erste Pol. Bei der Aufnahmefrequenz zählt nur der Abstand zu Fotos desselben Jahres.",
  "Remainder": "Rest",
  "Cumulative captures": "Kumulierte Aufnahmen",
  "New captures in year": "Neue Aufnahmen im Jahr",
  "Top 5 + other": "Top 5 + Rest",
  "Group": "Gruppe",
  "Cameras": "Kameras",
  "Mobile devices": "Mobilgeräte",
  "Top order": "Oben",
  "Largest contribution": "Größter Beitrag",
  "Newest devices": "Neueste Geräte",
  "No matching captures available.": "Keine passenden Aufnahmen vorhanden.",
  "Streamgraph of the five most frequent devices or manufacturers": "Streamgraph der fünf häufigsten Geräte oder Hersteller",
  "Through {year}": "Bis Jahr {year}",
  "In {year}": "Im Jahr {year}",
  "The top five depend on the selected metric and device type. Vertical order is recalculated each year, so ribbons cross when rankings change. “Other” groups all remaining devices.": "Die Top 5 beziehen sich auf die gewählte Kennzahl und Geräteart. Die vertikale Reihenfolge wird für jedes Jahr neu bestimmt; dadurch kreuzen sich Flächen bei Rangwechseln. „Rest“ fasst alle übrigen Geräte zusammen.",
  "No capture years available yet.": "Noch keine Aufnahmejahre vorhanden.",
  "Percentage change in captures year over year": "Veränderung der Aufnahmen zum Vorjahr in Prozent",
  "Captures by capture year": "Aufnahmen je Aufnahmejahr",
  "Captures by year of capture": "Aufnahmen nach Aufnahmejahr",
  "no previous-year value": "kein Vorjahreswert",
  "Captures are grouped by capture date, not import date. Hover also shows year-over-year change; the current year is incomplete.": "Aufnahmen nach Aufnahmedatum, nicht nach Importdatum. Der Hover zeigt auch die Veränderung zum Vorjahr; das laufende Jahr ist noch unvollständig.",
  "Loading Immich Insights…": "Lade Immich Insights …",
  "Accept invitation.": "Einladung annehmen.",
  "Welcome. Set up your account.": "Willkommen. Richte dein Konto ein.",
  "Welcome back.": "Willkommen zurück.",
  "Set your own password. Then you can add your Immich API key.": "Lege ein eigenes Passwort fest. Danach kannst du deinen Immich-API-Key hinterlegen.",
  "The first account automatically becomes admin and can invite others.": "Das erste Konto wird automatisch Admin und kann weitere Personen einladen.",
  "Sign in to see only your own library.": "Melde dich an, um nur deine eigene Bibliothek zu sehen.",
  "Name": "Name",
  "Email": "E-Mail",
  "Password": "Passwort",
  "Activate account": "Konto aktivieren",
  "Create admin account": "Admin-Konto erstellen",
  "Sign in": "Anmelden",
  "Use at least 12 characters for your password.": "Mindestens 12 Zeichen für dein Passwort.",
  "Profile saved.": "Profil gespeichert.",
  "Immich connection saved. Test it with the button now.": "Immich-Verbindung gespeichert. Prüfe sie jetzt mit dem Button.",
  "Password changed.": "Passwort geändert.",
  "New invitation link created for {name}.": "Neuer Einladungslink für {name} erstellt.",
  "{format} report": "{format}-Bericht",
  "Download {format}": "{format} herunterladen",
  "{count} matching captures · {shown} shown": "{count} passende Aufnahmen · {shown} angezeigt",
  "Original EXIF manufacturer names": "Originale EXIF-Herstellerbezeichnungen",
  "Included models": "Enthaltene Modelle",
  "Exposure": "Belichtung",
  "Your exposure triangle": "Dein Belichtungs-Dreieck",
  "Each dot is a photo with complete ISO, shutter, and aperture data. The closer it is to a corner, the more that parameter deviates from your usual value relative to the other two. In the center, all three influences are similar. This does not assess image quality or correct exposure.": "Jeder Punkt steht für ein Foto mit vollständigen ISO-, Zeit- und Blendendaten. Je näher er an einer Ecke liegt, desto stärker weicht dieser Parameter im Vergleich zu den anderen beiden von deinem üblichen Wert ab. In der Mitte sind die drei Einflüsse ähnlich stark – das ist keine Aussage über Bildqualität oder korrekte Belichtung.",
  "All years": "Alle Jahre",
  "Scale clipping": "Skalenbeschnitt",
  "Color": "Farbe",
  "Corner proximity": "Ecknähe",
  "Show axis values": "Achsenwerte zeigen",
  "Spread": "Spreizung",
  "Exposure triangle with {count} individual photo dots": "Belichtungs-Dreieck mit {count} einzelnen Fotopunkten",
  "High ISO": "ISO hoch",
  "Long shutter time": "Lange Verschlusszeit",
  "Wide aperture": "Offene Blende",
  "center": "Mitte",
  "high corner approx.": "hohe Ecke etwa",
  "Time": "Zeit",
  "long corner approx.": "lange Ecke etwa",
  "wide corner approx.": "offene Ecke etwa",
  "No photos with complete exposure data match this selection.": "Für diese Auswahl gibt es keine Fotos mit vollständigen Belichtungsdaten.",
  "High ISO value": "Hoher ISO-Wert",
  "More signal amplification helps in low light but can increase noise.": "Mehr Signalverstärkung hilft bei wenig Licht, kann aber Bildrauschen verstärken.",
  "The sensor gathers light for longer; motion can become blur or camera shake.": "Der Sensor sammelt länger Licht; Bewegung kann als Unschärfe oder Verwackeln sichtbar werden.",
  "A smaller f-number means a wider opening: more light and shallower depth of field, often with a blurrier background.": "Kleinere f-Zahl bedeutet größere Öffnung: mehr Lichteinfall und geringere Schärfentiefe, oft mit unschärferem Hintergrund.",
  "{count} dots shown": "{count} Punkte angezeigt",
  "{count} photos without a complete ISO/shutter/aperture trio": "{count} Fotos ohne vollständiges ISO-/Zeit-/Blenden-Trio",
  "Clipping limits outliers on the scale; no photo is hidden.": "Beschnitt begrenzt Ausreißer auf der Skala; kein Foto wird dadurch ausgeblendet.",
  "ISO-dominant": "ISO-lastig",
  "Shutter-dominant": "Zeit-lastig",
  "Aperture-dominant": "Blenden-lastig",
  "How to read this: start with a corner. A dot near “High ISO” has an unusually high ISO relative to its other two settings among your selected photos. Between corners, both settings stand out; near the center, all three are similar. ISO and shutter time use log₂ stops; aperture light effect uses −2 log₂(f-number). Each parameter is centered on its median; 95/99% clipping only limits extreme scale values. The three relative values are then blended into a triangle position. This chart does not show absolute brightness, correct exposure, or quality. Depth-of-field comparison additionally depends on sensor size, angle of view, focus distance, and output size; the EXIF f-number is not converted. Hover a dot for its exact EXIF values.": "Lesehilfe: Wähle zuerst eine Ecke. Ein Punkt nahe „ISO hoch“ hat im Vergleich zu den anderen beiden Merkmalen einen ungewöhnlich hohen ISO-Wert für deine ausgewählten Fotos. Zwischen zwei Ecken sind beide Merkmale auffällig; mittig sind sie ähnlich stark. ISO und Verschlusszeit werden in log₂-Stufen, die Lichtwirkung der Blende als −2 log₂(f-Zahl) berechnet. Pro Merkmal ist der Median die Mitte; 95/99 % begrenzen nur extreme Skalenwerte. Danach werden die drei relativen Werte zu einer Position im Dreieck gemischt. Das Diagramm zeigt weder absolute Helligkeit noch richtige Belichtung oder Qualität. Für die Schärfentiefe hängt die Vergleichbarkeit der Blende zusätzlich von Sensorgröße, Bildwinkel, Fokusabstand und Ausgabegröße ab; die tatsächliche f-Zahl im EXIF wird hier nicht umgerechnet. Berühre einen Punkt für seine konkreten EXIF-Werte.",
  "Area = number of {metric}": "Fläche = Anzahl {metric}",
  "Metric": "Kennzahl",
  "No matching devices available.": "Keine passenden Geräte vorhanden.",
  "Treemap of manufacturers and devices by {metric}": "Treemap der Hersteller und Geräte nach {metric}",
  "Each large area is a manufacturer; inner areas are devices. Click an area to view its assets.": "Jeder große Bereich ist ein Hersteller, die Unterflächen sind Geräte. Fläche anklicken, um die entsprechenden Assets zu sehen.",
  "No image dimensions available.": "Keine Bildabmessungen verfügbar.",
  "Confirm member deletion": "Mitglied löschen bestätigen",
  "About {count} A4 pages": "Etwa {count} DIN-A4-Seiten",
  "About {count} parking spaces (2.5 × 5 m)": "Etwa {count} Parkplätze à 2,5 × 5 m",
  "About {count} doubles tennis courts": "Etwa {count} Tennis-Doppelfelder",
  "h": "Std.",
  "min": "Min.",
  "s": "Sek.",
  "First photo with {device}": "Erstes Foto mit {device}",
  "Last photo with {device}": "Letztes Foto mit {device}",
  "{count}th {kind}": "{count}. {kind}",
  "asset": "Asset",
  "geotagged photo": "Foto mit Standort",
  "detected face": "erkanntes Gesicht",
  "First photo": "Erstes Foto",
  "First geotagged photo": "Erstes Foto mit Standort",
  "First photo with a person": "Erstes Foto mit Person",
  "First favorite": "Erster Favorit",
  "First video": "Erstes Video",
  "Shortest video": "Kürzestes Video",
  "Longest video": "Längstes Video",
  "Lowest ISO": "Niedrigster ISO-Wert",
  "Highest ISO": "Höchster ISO-Wert",
  "Shortest shutter time": "Kürzeste Verschlusszeit",
  "Longest shutter time": "Längste Verschlusszeit",
  "Widest aperture": "Offenste Blende",
  "Smallest aperture opening": "Kleinste Blendenöffnung",
  "Busiest photo day": "Tag mit den meisten Fotos",
  "Busiest video day": "Tag mit den meisten Videos",
  "Start of longest break": "Beginn der längsten Pause",
  "End of longest break": "Ende der längsten Pause",
  "Start of longest daily streak": "Beginn der längsten Tagesfolge",
  "End of longest daily streak": "Ende der längsten Tagesfolge",
  "{size} MB · largest known original file of this media type.": "{size} MB · größte bekannte Originaldatei dieser Medienart.",
  "{seconds} seconds · standalone video with known duration; Live Photo companion videos excluded.": "{seconds} Sekunden · eigenständiges Video mit bekannter Laufzeit; Live-Photo-Begleitvideos ausgeschlossen.",
  "Earliest dated capture in your library.": "Die früheste datierte Aufnahme deiner Bibliothek.",
  "Latest dated capture in your library.": "Die jüngste datierte Aufnahme deiner Bibliothek.",
  "First dated medium of this type.": "Erstes datiertes Medium dieser Art.",
  "First dated photo with this device.": "Erstes datiertes Foto mit diesem Gerät.",
  "Latest dated photo with this device.": "Jüngstes datiertes Foto mit diesem Gerät.",
  "{value} · only photo with this extreme value.": "{value} · einziges Foto mit diesem Extremwert.",
  "{count} {kind} on this capture day.": "{count} {kind} an diesem Aufnahmetag.",
  "Followed by {days} calendar days without a dated capture.": "Danach folgen {days} Kalendertage ohne datierte Aufnahme.",
  "First capture after {days} calendar days without a dated capture.": "Erste Aufnahme nach {days} Kalendertagen ohne datierte Aufnahme.",
  "Captures were made on {days} consecutive days.": "An {days} aufeinanderfolgenden Tagen entstanden Aufnahmen.",
  "Last day of a {days}-day capture streak.": "Letzter Tag einer Folge von {days} Aufnahmetagen.",
  "Counted chronologically by capture time; undated media are excluded. ": "Chronologisch nach Aufnahmezeit gezählt; Medien ohne Aufnahmedatum bleiben außen vor. ",
  "Counted chronologically by capture time; undated media are excluded. Multiple faces in one photo count separately; they are not distinct people.": "Chronologisch nach Aufnahmezeit gezählt; Medien ohne Aufnahmedatum bleiben außen vor. Mehrere Gesichter auf einem Foto zählen einzeln; es sind keine unterschiedlichen Personen.",
  "GPS altitude": "GPS-Höhe",
  "the selected asset only": "genau das ausgewählte Asset",
  "captured with device “{name}”": "aufgenommen mit dem Gerät „{name}“",
  "captured with devices of EXIF manufacturer “{name}”": "aufgenommen mit Geräten des EXIF-Herstellers „{name}“",
  "captured with devices of grouped manufacturer “{name}”": "aufgenommen mit Geräten des zusammengefassten Herstellers „{name}“",
  "{lower} through {upper}": "{lower} bis einschließlich {upper}",
  "{lower} to under {upper}": "{lower} bis unter {upper}",
  "with {field} in range {interval} {unit}": "mit {field} im Bereich {interval} {unit}",
  "in portrait orientation": "im Hochformat",
  "in landscape orientation": "im Querformat",
  "with square or undetermined orientation": "mit quadratischem oder nicht bestimmbarem Bildformat",
  "with dimensions {width} × {height} pixels": "mit Bildabmessungen {width} × {height} Pixel",
  "captured on {date}": "aufgenommen am {date}",
  "captured on {date} (all years)": "aufgenommen an einem {date} (alle Jahre)",
  "captured from {start} through {end} (inclusive)": "aufgenommen vom {start} bis {end} (einschließlich)",
  "captured on {weekday} between {hour}": "aufgenommen am {weekday} zwischen {hour}",
  "captured in {month} (all years)": "aufgenommen im Monat {month} (alle Jahre)",
  "captured on a {weekday} (all years)": "aufgenommen an einem {weekday} (alle Jahre)",
  "captured between {hour} (all days)": "aufgenommen zwischen {hour} (alle Tage)",
  "captured in {year}": "aufgenommen im Jahr {year}",
  "device “{name}”": "Gerät „{name}“",
  "with camera “{name}”": "mit der Kamera „{name}“",
  "EXIF manufacturer “{name}”": "EXIF-Hersteller „{name}“",
  "manufacturer “{name}”": "Hersteller „{name}“",
  "category {category}": "Kategorie {category}",
  "favorites only": "nur Favoriten",
  "with location data": "mit Standortdaten",
  "with detected people": "mit erkannter Person",
  "with a usable value for {field}": "mit auswertbarem Wert für {field}",
  "square/unknown": "quadratisch/unklar",
  " in {year}": " im Jahr {year}",
  " from {start} through {end}": " vom {start} bis {end}",
  "Your {metric}{scope}: {detail}. Capture times follow the local date in Immich.": "Eigene {metric}{scope}: {detail}. Aufnahmezeiten entsprechen dem lokalen Datum in Immich.",
  "Request failed.": "Anfrage fehlgeschlagen.",
  "Device assignments could not be recalculated. The previous snapshot remains available.": "Gerätezuordnung konnte nicht neu berechnet werden. Der letzte Datenstand bleibt erhalten.",
  "Sync failed. Check the connection and API permissions. The last complete snapshot remains available.": "Abgleich fehlgeschlagen. Verbindung und API-Berechtigungen prüfen. Der letzte vollständige Stand bleibt erhalten.",
  "Snapshot from an older version. Please select “Refresh now”.": "Datenstand aus einer älteren Version. Bitte „Jetzt aktualisieren“ starten.",
  "Sync interrupted by a restart. Please refresh again.": "Abgleich durch Neustart unterbrochen. Bitte erneut aktualisieren.",
  "No snapshot yet. Please start a refresh.": "Noch kein Datenstand. Bitte einmal „Aktualisieren“ starten.",
  "Invalid device or date-range filter.": "Ungültiger Geräte- oder Zeitraumfilter.",
  "Choose a specific EXIF device.": "Bitte ein konkretes EXIF-Gerät auswählen.",
  "Device name and manufacturer cannot both be empty.": "Gerätename und Hersteller dürfen nicht leer sein.",
  "Enter at least one correction.": "Bitte mindestens eine Korrektur angeben.",
  "Please wait until the current sync finishes.": "Bitte warte, bis der laufende Abgleich fertig ist.",
  "Snapshot changed during export. Please try again.": "Datenstand wurde während des Exports aktualisiert. Bitte erneut versuchen.",
  "No statistics available yet.": "Noch keine Statistik verfügbar.",
  "Unknown export format.": "Unbekanntes Exportformat.",
  "Setup is already complete.": "Die Einrichtung ist bereits abgeschlossen.",
  "Enter a name.": "Bitte gib einen Namen ein.",
  "Setup has already been completed.": "Die Einrichtung wurde bereits abgeschlossen.",
  "Email or password is incorrect.": "E-Mail oder Passwort ist falsch.",
  "This invitation link is invalid or expired.": "Dieser Einladungslink ist ungültig oder abgelaufen.",
  "Only the admin can list users.": "Nur der Admin kann Benutzer auflisten.",
  "This email address is already in use.": "Diese E-Mail-Adresse ist bereits vergeben.",
  "Pending invitation not found.": "Offene Einladung nicht gefunden.",
  "Type delete to confirm.": "Zur Bestätigung bitte delete eingeben.",
  "Member not found.": "Mitglied nicht gefunden.",
  "An admin account cannot be deleted here.": "Ein Admin-Konto kann hier nicht gelöscht werden.",
  "Sync is still running. Please try again afterward.": "Der Abgleich läuft noch. Bitte danach erneut versuchen.",
  "Name or profile icon is invalid.": "Name oder Profil-Icon ist ungültig.",
  "Current password is incorrect.": "Das bisherige Passwort ist falsch.",
  "First save your Immich URL and API key in your profile.": "Bitte hinterlege zuerst deine Immich-URL und deinen API-Key im Profil.",
  "The stored API key cannot be decrypted.": "Der gespeicherte API-Key kann nicht entschlüsselt werden.",
  "Immich is unreachable from the backend. Check the URL and Docker network.": "Immich ist vom Backend nicht erreichbar. Prüfe URL und Docker-Netzwerk.",
  "Immich could not be queried. Check the connection and try again.": "Immich konnte nicht abgefragt werden. Prüfe die Verbindung und versuche es erneut.",
  "Invalid year selection.": "Ungültige Jahresauswahl.",
  "Enter a valid date range.": "Bitte gib einen gültigen Zeitraum ein.",
  "Image not found.": "Bild nicht gefunden.",
  "No Immich profile image available.": "Kein Immich-Profilbild verfügbar.",
  "Please sign in.": "Bitte melde dich an.",
  "Please sign in again.": "Bitte melde dich erneut an.",
  "Invalid form protection. Reload the page.": "Ungültiger Formularschutz. Bitte lade die Seite neu.",
  "Only the admin can invite users.": "Nur der Admin kann Benutzer einladen.",
  "Asset ID is missing.": "Asset-ID fehlt.",
  "Device or manufacturer is missing.": "Gerät oder Hersteller fehlt.",
  "Distribution range is missing.": "Verteilungsbereich fehlt.",
  "Invalid value range.": "Ungültiger Wertebereich.",
  "Capture date is missing.": "Aufnahmedatum fehlt.",
  "Invalid capture date.": "Ungültiges Aufnahmedatum.",
  "Invalid anniversary date.": "Ungültiger Jahrestag.",
  "Invalid calendar week.": "Ungültige Kalenderwoche.",
  "Time filter is incomplete.": "Zeitfilter unvollständig.",
  "Invalid device category.": "Ungültige Gerätekategorie.",
  "Image orientation is missing.": "Bildformat fehlt.",
  "Image dimensions are missing.": "Bildabmessungen fehlen.",
  "Invalid date-range restriction.": "Ungültige Zeitraum-Einschränkung.",
  "Number format": "Zahlenformat",
  "Focal length": "Brennweite",
  "This changes separators in statistics and charts, not the stored values.": "Die Einstellung ändert Trennzeichen in Kennzahlen und Diagrammen, nicht die gespeicherten Werte.",
  "Thousands and decimal separators": "Tausender- und Dezimaltrennzeichen",
  "Media marked as favorites": "Als Favorit markierte Medien",
  "Original sizes of all photos, when complete": "Originalgrößen aller Fotos, sofern vollständig",
  "Original sizes of all videos, when complete": "Originalgrößen aller Videos, sofern vollständig",
  "Only when all original sizes are known": "Nur bei vollständig bekannten Originalgrößen",
  "Only when all photo sizes are known": "Nur bei vollständig bekannten Fotogrößen",
  "Only when all video sizes are known": "Nur bei vollständig bekannten Videogrößen",
  "Photos with at least one detected face": "Fotos mit mindestens einem erkannten Gesicht",
  "Unique person IDs in the snapshot": "Eindeutige Personen-IDs im Datenstand",
  "Only photos with detected faces": "Nur Fotos mit erkannten Gesichtern",
  "Including photos without detected faces": "Auch Fotos ohne erkannte Gesichter",
  "Assets with latitude and longitude": "Assets mit Breiten- und Längengrad",
  "No country information available": "Keine Länderangaben verfügbar",
  "No continents can be determined": "Keine Kontinente ermittelbar",
  "Automatic for language": "Automatisch nach Sprache",
  "Preview": "Vorschau",
  "Notes": "Hinweise",
  "About this project & what is next": "Über das Projekt & Ausblick",
  "Immich Insights began with a simple idea: make full use of the control you have over your own photos and videos. It turns library data into new perspectives on your memories, especially for a personal year-in-review.": "Immich Insights entstand aus einer einfachen Idee: die Hoheit über die eigenen Fotos und Videos bewusst zu nutzen. Die Daten deiner Bibliothek eröffnen neue Blickwinkel auf deine Erinnerungen – besonders für einen persönlichen Jahresrückblick.",
  "Understanding metadata": "Metadaten verstehen",
  "EXIF is not always consistent: manufacturers and devices store some details differently or omit them. Immich exposes selected, processed EXIF fields through its asset API, but not a general raw EXIF dump.": "EXIF ist nicht immer einheitlich: Hersteller und Geräte schreiben manche Angaben unterschiedlich oder gar nicht. Immich stellt über die Asset-API ausgewählte, aufbereitete EXIF-Felder bereit, aber keinen allgemeinen Roh-EXIF-Dump.",
  "An optional raw-metadata import or additional Immich API fields could eventually show flash usage, camera directions as a compass rose, and GPS altitudes as a hypsometric curve. Some original metadata also includes a 35 mm-equivalent focal length or camera details needed to derive one. Where available, it could make focal lengths and actual angles of view more comparable across cameras. We do not guess when reliable data is unavailable.": "Mit einem späteren, optionalen Rohdaten-Import oder zusätzlichen Immich-API-Feldern wären etwa Blitz-Nutzung, Blickrichtungen als Windrose und GPS-Höhen als hypsometrische Kurve denkbar. Manche Originalmetadaten enthalten zudem eine 35-mm-äquivalente Brennweite oder Kameradaten, mit denen sie sich bestimmen lässt. Falls verfügbar, könnten damit Brennweiten und tatsächliche Bildwinkel verschiedener Kameras sinnvoller verglichen werden. Wo verlässliche Angaben fehlen, erfinden wir keine Werte.",
  "Planned ideas": "Geplante Ideen",
  "Filterable maps could highlight special captures such as your southernmost photo. Small Immich thumbnails could later reveal your personal color palette without permanently copying original files.": "Filterbare Karten könnten besondere Aufnahmen wie das südlichste Foto zeigen. Kleine Immich-Vorschaubilder könnten später eine persönliche Farbpalette ermöglichen, ohne Originaldateien dauerhaft zu kopieren.",
  "A simple photo-book integration is another idea: a page or two could enrich your year-in-review with selected statistics.": "Eine einfache Fotobuch-Anbindung ist ebenfalls eine Idee: Ein oder zwei Seiten könnten deinen Jahresrückblick mit ausgewählten Statistiken ergänzen.",
  "We are currently improving performance and working on more useful, better-looking downloads. The project will keep evolving; ideas and bug reports are welcome.": "Wir arbeiten derzeit an weiterer Optimierung und an nützlicheren, schöner gestalteten Downloads. Das Projekt wird weiterentwickelt; Ideen und Fehlermeldungen sind willkommen.",
  "Made with AI, shaped by people": "Mit KI entwickelt, von Menschen gestaltet",
  "AI tools helped build parts of Immich Insights. The concept, product decisions, verification, and ongoing care still require substantial human work. It is not meant to replace Immich as a full-featured media viewer; it shows what your library data can reveal from another perspective.": "KI-Werkzeuge haben bei Teilen der Umsetzung geholfen. Konzept, Produktentscheidungen, Prüfung und Pflege erfordern dennoch viel menschliche Arbeit. Immich Insights soll Immich nicht als vollwertigen Medienbetrachter ersetzen, sondern zeigen, welche neuen Perspektiven die Daten deiner Bibliothek eröffnen können.",
  "Run it safely": "Sicher betreiben",
  "This instance contains private library and location data. Prefer running it only on your home network; do not expose it directly to the internet. If remote access is necessary, use at least HTTPS and strong access controls.": "Diese Instanz enthält private Bibliotheks- und Standortdaten. Betreibe sie vorzugsweise nur im Heimnetz und veröffentliche sie nicht direkt im Internet. Falls ein externer Zugriff nötig ist, nutze mindestens HTTPS und sichere Zugangskontrollen.",
  "Tips for meaningful statistics": "Tipps für aussagekräftige Statistiken",
  "Accurate capture dates matter most: incorrect timestamps distort years, streaks, and maps. Keep screenshots separate from memory photos where possible. In large libraries, favorites often help more than hasty deletion.": "Korrekte Aufnahmedaten sind die wichtigste Grundlage: Falsche Zeitstempel verfälschen Jahre, Streaks und Karten. Trenne Screenshots nach Möglichkeit von Erinnerungsfotos. In großen Bibliotheken helfen Favoriten oft mehr als vorschnelles Löschen.",
  "Support on Buy Me a Coffee": "Auf Buy Me a Coffee unterstützen",
  "Open an issue or share feedback": "Issue eröffnen oder Feedback geben",
  "Found a bug or have an idea? Open a GitHub issue. If you would also like to support further development, a coffee is appreciated but never required.": "Du hast einen Fehler gefunden oder eine Idee? Eröffne dafür gern ein GitHub-Issue. Wenn du die Weiterentwicklung zusätzlich unterstützen möchtest, freue ich mich über einen Kaffee – nötig ist das natürlich nicht.",
  "Format": "Format",
};
