// Spanish translations; keys are the English UI copy.
export const spanish: Record<string, string> = {
  "Preparing": "Preparando",
  "Checking albums": "Comprobando álbumes",
  "Device assignments complete": "Asignación de dispositivos completada",
  "Immich returned HTTP {status}. Check the URL, API key, and permissions.": "Immich respondió con HTTP {status}. Comprueba la URL, la clave API y los permisos.",
  "Immich denied {permission} ({operation}).": "Immich denegó {permission} ({operation}).",
  "Assets": "Archivos",
  "Administrator": "Administrador",
  "Export": "Exportación",
  "captures. Click to view assets.": "capturas. Haz clic para ver los archivos.",
  "Average photo resolution by capture year in megapixels": "Resolución fotográfica media por año de captura en megapíxeles",
  "Schematic fields of view for the five most frequent original EXIF focal lengths": "Conos esquemáticos del ángulo de visión de las cinco distancias focales EXIF originales más frecuentes",
  "Library timeline": "Cronología de la biblioteca",
  "{year}: average {mp} megapixels across {count} photos": "{year}: media de {mp} megapíxeles en {count} fotos",
  "{year}: view values": "{year}: ver valores",
  "Captures by device: {metric}": "Capturas por dispositivo: {metric}",
  "percent": "por ciento",
  "Frequency distribution of {name}": "Distribución de frecuencias de {name}",
  "{year}: view captures": "{year}: ver capturas",
  "Average MB per file by capture year": "MB medios por archivo y año de captura",
  "Cumulative media by capture year": "Archivos acumulados por año de captura",
  "Portrait format": "Vertical",
  "cumulative": "acumulado",
  "dark": "oscuro",
  "device": "dispositivo",
  "hour": "hora",
  "landscape": "horizontal",
  "logarithmic scale": "logarítmico",
  "media": "archivos",
  "month": "mes",
  "photos": "fotos",
  "portrait": "vertical",
  "year": "año",
  "assets": "archivos",
  "Library": "Biblioteca",
  "Year highlights": "Destacados del año",
  "Date range": "Período",
  "Photo profile": "Perfil fotográfico",
  "Download": "Descargas",
  "Profile": "Perfil",
  "Your photo library,": "Tu fototeca,",
  "at a glance.": "de un vistazo.",
  "in total": "en total",
  "Newest photo": "Foto más reciente",
  "Avg. per asset": "Media por archivo",
  "Avg. per photo": "Media por foto",
  "Avg. per video": "Media por vídeo",
  "Sign out": "Cerrar sesión",
  "Member": "Miembro",
  "Your account": "Tu cuenta",
  "Display name": "Nombre visible",
  "Profile icon": "Icono del perfil",
  "Save profile": "Guardar perfil",
  "Private to you": "Solo para ti",
  "Immich connection": "Conexión con Immich",
  "No API key saved": "No hay clave API guardada",
  "API key saved": "Clave API guardada",
  "No Immich URL saved yet": "Aún no hay URL de Immich guardada",
  "New API key": "Nueva clave API",
  "Save connection": "Guardar conexión",
  "Test connection": "Comprobar conexión",
  "Replace API key": "Sustituir clave API",
  "Cancel": "Cancelar",
  "Security": "Seguridad",
  "Change password": "Cambiar contraseña",
  "Current password": "Contraseña actual",
  "New password": "Nueva contraseña",
  "Administration": "Administración",
  "Invite a member": "Invitar a alguien",
  "Create invitation link": "Crear enlace de invitación",
  "Share link": "Compartir enlace",
  "Copy": "Copiar",
  "Invited": "Invitado",
  "New link": "Nuevo enlace",
  "Delete": "Eliminar",
  "Permanently delete member": "Eliminar miembro definitivamente",
  "To confirm, type": "Para confirmar, escribe",
  "Data export": "Exportación de datos",
  "Your library": "Tu biblioteca",
  "Your date range": "Tu período",
  "Your photo profile": "Tu perfil fotográfico",
  "Download your data": "Descarga tus datos",
  "Entire library": "Biblioteca completa",
  "A year of memories": "Un año lleno de recuerdos",
  "Year": "Año",
  "From": "Desde",
  "To": "Hasta",
  "Refresh now": "Actualizar ahora",
  "Overview": "Resumen",
  "Evolution": "Evolución",
  "Unknown device": "Dispositivo desconocido",
  "Unknown manufacturer": "Fabricante desconocido",
  "Your media": "Tus archivos",
  "total assets": "archivos en total",
  "Favorites": "Favoritos",
  "Your albums": "Tus álbumes",
  "Assets without album": "Archivos sin álbum",
  "Original files": "Archivos originales",
  "Storage": "Almacenamiento",
  "Total storage": "Almacenamiento total",
  "Photo storage": "Espacio de fotos",
  "Video storage": "Espacio de vídeos",
  "Image formats": "Formatos de imagen",
  "Which image dimensions occur?": "¿Qué dimensiones tienen tus imágenes?",
  "Metadata": "Metadatos",
  "People": "Personas",
  "Places": "Lugares",
  "Time span": "Período",
  "From the beginning to today": "Desde el principio hasta hoy",
  "Cameras & devices": "Cámaras y dispositivos",
  "What was it shot with?": "¿Con qué se capturó?",
  "Correct devices": "Corregir dispositivos",
  "No device information available.": "No hay datos de dispositivos.",
  "Exposure settings distribution": "Distribución de parámetros de captura",
  "Focal length comparison": "Comparación de distancias focales",
  "Your five most common angles of view": "Tus cinco ángulos de visión más frecuentes",
  "Time of day": "Hora del día",
  "Month": "Mes",
  "Photos": "Fotos",
  "Videos": "Vídeos",
  "All devices": "Todos los dispositivos",
  "Camera": "Cámara",
  "Mobile device": "Dispositivo móvil",
  "Other": "Otros",
  "With location": "Con ubicación",
  "With person": "Con personas",
  "Linear": "Lineal",
  "Logarithmic": "Logarítmica",
  "Scale": "Escala",
  "Open profile": "Abrir perfil",
  "Device": "Dispositivo",
  "Exposure time": "Tiempo de exposición",
  "Video length": "Duración del vídeo",
  "Your five most frequent original focal lengths": "Tus cinco distancias focales originales más frecuentes",
  "Loading focal lengths from stored EXIF values…": "Cargando distancias focales de los valores EXIF guardados…",
  "Focal lengths are taken unchanged from each photo’s focalLength. Click a bar to see those exact assets. The device filter only reads the stored snapshot.": "Las distancias focales proceden sin cambios del campo focalLength de cada foto. Haz clic en una barra para ver los archivos. El filtro de dispositivo solo consulta los datos guardados.",
  "Use Immich profile photo": "Usar foto de perfil de Immich",
  "Choose your Immich profile photo or an app icon. The Immich photo requires the optional avatar permission.": "Elige tu foto de perfil de Immich o uno de los iconos de la aplicación. La foto de Immich requiere el permiso opcional de avatar.",
  "Checking connection…": "Comprobando conexión…",
  "Last checked": "Última comprobación",
  "Checking…": "Comprobando…",
  "Immich is reachable. Only your own assets are counted.": "Immich está disponible. Solo se cuentan tus propios archivos.",
  "Volumes by year": "Cantidades por año",
  "How are your captures distributed?": "¿Cómo se distribuyen tus capturas?",
  "Total": "Total",
  "Average per capture year": "Media por año de captura",
  "Captures by year": "Capturas por año",
  "Assets with a person": "Archivos con personas",
  "Assets with location": "Archivos con ubicación",
  "of the total": "del total",
  "Click to view matching assets": "Haz clic para ver los archivos correspondientes",
  "Technique & time": "Técnica y tiempo",
  "For perspective": "Para imaginarlo",
  "Your library in numbers": "Tu biblioteca en cifras",
  "Captures": "Capturas",
  "Average photo resolution": "Resolución media de las fotos",
  "Most common ISO": "ISO más frecuente",
  "Most common focal length": "Distancia focal más frecuente",
  "Most common shutter speed": "Velocidad de obturación más frecuente",
  "Total video duration": "Duración total de vídeos",
  "Average video length": "Duración media de vídeo",
  "Cumulative exposure time": "Tiempo de exposición acumulado",
  "Photos with people": "Fotos con personas",
  "Categorized people": "Personas clasificadas",
  "Total detected people": "Personas detectadas en total",
  "Avg. people per photo with people": "Media de personas por foto con personas",
  "Avg. people per photo overall": "Media de personas por foto en total",
  "Assets with location data": "Archivos con ubicación",
  "Countries with location data": "Países con ubicación",
  "Continents with location data": "Continentes con ubicación",
  "Africa": "África",
  "Antarctica": "Antártida",
  "Asia": "Asia",
  "Europe": "Europa",
  "North America": "América del Norte",
  "South America": "América del Sur",
  "Oceania": "Oceanía",
  "File size": "Tamaño del archivo",
  "Original size unknown": "Tamaño original desconocido",
  "First capture": "Primera captura",
  "Last capture": "Última captura",
  "Busiest day": "Día con más archivos",
  "Days with photos": "Días con fotos",
  "Longest break": "Pausa más larga",
  "Longest daily streak": "Racha diaria más larga",
  "Longest weekly streak": "Racha semanal más larga",
  "Portrait and landscape": "Vertical y horizontal",
  "Portrait": "Vertical",
  "Landscape": "Horizontal",
  "Unknown / square": "Desconocido / cuadrado",
  "Image quality over time": "Calidad de imagen a lo largo del tiempo",
  "Photo resolution by capture year": "Resolución por año de captura",
  "EXIF over time": "EXIF a lo largo del tiempo",
  "Exposure settings by year": "Parámetros de captura por año",
  "Captures per year & year-over-year change": "Capturas por año y cambio interanual",
  "Device development": "Evolución de dispositivos",
  "Which devices shaped your years?": "¿Qué dispositivos marcaron tus años?",
  "Annual contribution": "Contribución anual",
  "Who contributed to the year?": "¿Qué dispositivo contribuyó cada año?",
  "Your tendencies": "Tus tendencias",
  "Between two poles · by year": "Entre dos polos · por año",
  "Tendency score": "Valor de tendencia",
  "Area comparison": "Comparación de áreas",
  "Manufacturers and devices": "Fabricantes y dispositivos",
  "Donut chart": "Gráfico de anillo",
  "When do you capture your media?": "¿Cuándo capturas tus fotos y vídeos?",
  "{hour} · {count} captures": "{hour} · {count} capturas",
  "Name and profile image are saved automatically. The Immich photo requires the optional avatar permission.": "El nombre y la imagen de perfil se guardan automáticamente. La foto de Immich requiere el permiso opcional para avatares.",
  "When?": "¿Cuándo?",
  "By month": "Por mes",
  "By weekday": "Por día de la semana",
  "By hour": "Por hora del día",
  "{hour} · {count} assets": "{hour} · {count} archivos",
  "{focal} mm: view {count} photos": "{focal} mm: ver {count} fotos",
  "EXIF by time of day and month": "EXIF por hora del día y mes",
  "Aperture": "Apertura",
  "Back to statistics": "Volver a las estadísticas",
  "Assets in stored snapshot": "Archivos en los datos guardados",
  "Matching media": "Archivos coincidentes",
  "Searching matching assets in the local cache…": "Buscando archivos coincidentes en la caché local…",
  "No assets are stored for this filter.": "No hay archivos guardados para este filtro.",
  "Load 36 more": "Cargar 36 más",
  "Loading…": "Cargando…",
  "Capture date unknown": "Fecha de captura desconocida",
  "Thumbnails are loaded from Immich on demand. The selection and counts come from your stored profile snapshot.": "Las miniaturas se cargan de Immich cuando hacen falta. La selección y los recuentos proceden de los datos guardados de tu perfil.",
  "Enable light mode": "Activar modo claro",
  "Enable dark mode": "Activar modo oscuro",
  "Light": "Claro",
  "Dark": "Oscuro",
  "required": "obligatorio",
  "optional": "opcional",
  "Read owned assets and their EXIF, people, and location data": "Leer tus archivos y sus datos EXIF, de personas y de ubicación",
  "Read Immich user ID to exclude shared assets": "Leer el ID de usuario de Immich para excluir archivos compartidos",
  "Load missing file sizes and verify thumbnails": "Obtener tamaños de archivo faltantes y proteger las miniaturas",
  "Display a thumbnail of your latest photo": "Mostrar la miniatura de tu foto más reciente",
  "Adopt Immich profile photo": "Usar la foto de perfil de Immich",
  "Count owned albums": "Contar tus álbumes",
  "Total binary digits": "Bits totales",
  "As grains of sand": "Como granos de arena",
  "All photos as 10 × 15 cm prints": "Todas las fotos impresas a 10 × 15 cm",
  "Height of the print stack": "Altura de la pila de fotos",
  "Weight of all prints": "Peso de todas las copias",
  "Capture year": "Año de captura",
  "Years": "Años",
  "Days": "Días",
  "capture month": "Mes de captura",
  "Cumulative by": "Acumulado por",
  "Average by": "Media por",
  "MB per file": "MB por archivo",
  "of": "de los",
  "Invitees set their own password. You cannot see their libraries or API keys.": "Los invitados eligen su propia contraseña. No puedes ver sus bibliotecas ni sus claves API.",
  "This link is shown only now and expires in 7 days.": "El enlace solo se muestra ahora y caduca en 7 días.",
  "permanently delete?": "¿eliminar definitivamente?",
  "enter": "escribir",
  "Sessions, API key, cache, statistics, and device corrections for this account are deleted from the database. Immich originals are untouched.": "Se eliminarán de la base de datos las sesiones, la clave API, la caché, las estadísticas y las correcciones de dispositivos de esta cuenta. Los originales de Immich no se modifican.",
  "Your timeline": "Tu cronología",
  "Notable moments on a timeline": "Momentos destacados en una línea de tiempo",
  "From the first photo to device changes, records, and milestones. Everything follows the capture date in Immich.": "De la primera foto a cambios de dispositivo, récords e hitos. Todo sigue la fecha de captura de Immich.",
  "Category": "Categoría",
  "All events": "Todos los eventos",
  "Search": "Buscar",
  "Device or event": "Dispositivo o evento",
  "Control timeline": "Controlar la línea de tiempo",
  "Zoom out": "Reducir",
  "Zoom in": "Ampliar",
  "Everything": "Todo",
  "Recent": "Más recientes",
  "First & last": "Primera y última",
  "Devices": "Dispositivos",
  "Milestones": "Hitos",
  "Records": "Récords",
  "Breaks": "Pausas",
  "View matching assets": "Ver archivos correspondientes",
  "Gramps Web open-source project": "Proyecto de código abierto Gramps Web",
  "Many thanks to its team for their excellent work!": "¡Gracias al equipo por su excelente trabajo!",
  "Use the mouse wheel to zoom and drag to pan. Colors mark event types; click grouped points repeatedly to cycle through them.": "Usa la rueda para ampliar y arrastra para desplazarte. Los colores distinguen tipos de eventos; los puntos agrupados se pueden pulsar varias veces.",
  "Use the mouse wheel to zoom and drag to pan. Click a point or label to view matching assets.": "Usa la rueda para ampliar y arrastra para desplazarte. Haz clic en un punto o etiqueta para ver los archivos correspondientes.",
  "events in view": "Eventos visibles",
  "No events for this selection.": "No hay eventos para esta selección.",
  "Timeline: mouse wheel zooms, drag or swipe pans, arrow keys navigate": "Línea de tiempo: rueda para ampliar, arrastra o desliza para mover y usa las flechas para navegar",
  "ISO, focal length & aperture by {axis}": "ISO, distancia focal y apertura por {axis}",
  "Appearance & language": "Apariencia e idioma",
  "Accent color": "Color de acento",
  "Green": "Verde",
  "Purple": "Morado",
  "Blue": "Azul",
  "Amber": "Ámbar",
  "Chart palette": "Paleta de gráficos",
  "Balanced": "Equilibrada",
  "Vivid": "Intensa",
  "Calm": "Suave",
  "Aurora": "Aurora",
  "Colorblind-friendly": "Apta para daltonismo",
  "Language": "Idioma",
  "Immich API key permissions": "Permisos de la clave API de Immich",
  "Grant these permissions when creating the key in Immich. The list is based on the backend API calls.": "Concede estos permisos al crear la clave en Immich. La lista se basa en las llamadas API del servidor.",
  "Albums created by you": "Álbumes creados por ti",
  "Albums with at least one asset in this period": "Álbumes con al menos un archivo en este período",
  "Album membership unavailable": "No se dispone de la asignación a álbumes",
  "{photos} photos · {videos} videos": "{photos} fotos · {videos} vídeos",
  "Original files according to Immich": "Archivos originales según Immich",
  "{count} file sizes missing": "Falta el tamaño de {count} archivos",
  "Others": "Otros",
  "Photo": "Foto",
  "Video": "Vídeo",
  "ISO, focal length & aperture by time of day": "ISO, distancia focal y abertura por hora del día",
  "ISO, focal length & aperture by month": "ISO, distancia focal y abertura por mes",
  "Number of bits in the original files": "Número de bits de los archivos originales",
  "Illustrative time comparison": "Comparación de tiempo ilustrativa",
  "1 bit = 1 grain (Ø 0.25 mm, 64% packing)": "1 bit = 1 grano (Ø 0,25 mm, empaquetado al 64 %)",
  "0.2 mm per 10 × 15 cm print": "0,2 mm por copia de 10 × 15 cm",
  "2 g per 10 × 15 cm print": "2 g por copia de 10 × 15 cm",
  "Estimate at 7 cents per 10 × 15 cm print, excluding shipping": "Estimación de 7 céntimos por copia de 10 × 15 cm, sin envío",
  "Priceless": "Incalculable",
  "with known resolution": "con resolución",
  "{count} photos with exactly this value": "{count} fotos con este valor exacto",
  "{count} standalone videos with known duration": "{count} vídeos independientes con duración conocida",
  "{count} photos with shutter speed": "{count} fotos con velocidad de obturación",
  "All image formats": "Todos los formatos de imagen",
  "Very large formats are fitted for display only; their aspect ratio stays unchanged.": "Los formatos muy grandes solo se ajustan para mostrarlos; su relación de aspecto se conserva.",
  "Minimum per format": "Mínimo por formato",
  "No image format reaches this minimum.": "Ningún formato alcanza este mínimo.",
  "{visible} of {total} image formats shown · {matches} matching photos. Set the minimum to 1 to show every format matching the filter.": "{visible} de {total} formatos visibles · {matches} fotos coincidentes. El mínimo 1 muestra todos los formatos del filtro.",
  "{covered} of {photos} photos have stored dimensions.": "{covered} de {photos} fotos tienen dimensiones guardadas.",
  "{count} videos without duration": "{count} vídeos sin duración",
  "Only standalone videos with known duration": "Solo vídeos independientes con duración conocida",
  "{count} photos without shutter speed": "{count} fotos sin tiempo de exposición",
  "Person associations across all assets": "Asignaciones de personas en todos los archivos",
  "Most common: {country} ({count} assets)": "Más frecuente: {country} ({count} archivos)",
  "Days with photos {year}": "Días con fotos en {year}",
  "{count} days": "{count} días",
  "{count} weeks": "{count} semanas",
  "{percent}% of {count} calendar days": "{percent} % de {count} días naturales",
  " · first to last capture": " · de la primera a la última captura",
  "{count} assets without capture date": "{count} archivos sin fecha de captura",
  "{start} to {end}": "Del {start} al {end}",
  "Snapshot: {date}": "Datos de: {date}",
  "No snapshot saved yet.": "Aún no hay datos guardados.",
  "Immich is syncing in the background. The previous snapshot remains available.": "Immich se sincroniza en segundo plano. Los datos anteriores siguen disponibles.",
  "A database sync can take a long time for a large library. You can continue using the page; the previous snapshot remains available until the new one is complete.": "La sincronización puede tardar bastante con una biblioteca grande. Puedes seguir usando la página; los datos anteriores se conservan hasta que termine.",
  "Stored snapshot": "Instantánea guardada",
  "Connect your Immich account first.": "Primero conecta tu cuenta de Immich.",
  "Save your Immich URL and personal API key in your profile.": "Guarda la URL de Immich y tu clave API personal en el perfil.",
  "Go to profile": "Ir al perfil",
  "The SQLite file contains cached assets, statistics, album IDs, and your device corrections. PDF, CSV, and JPG are compact reports. Passwords, API keys, and original images are excluded from every export.": "El archivo SQLite contiene archivos en caché, estadísticas, ID de álbumes y correcciones de dispositivos. PDF, CSV y JPG son informes compactos. Ninguna exportación incluye contraseñas, claves API ni imágenes originales.",
  "Refresh the library first.": "Primero actualiza la biblioteca.",
  "Choose start and end dates.": "Elige las fechas de inicio y fin.",
  "Both start and end dates are included.": "Se incluyen ambos días.",
  "Initial sync in progress…": "Sincronización inicial en curso…",
  "Scan the library once": "Analizar la biblioteca por primera vez",
  "Use “Refresh now” to start the background sync.": "Pulsa «Actualizar ahora» para iniciar la sincronización en segundo plano.",
  "Calculating library statistics…": "Calculando estadísticas de la biblioteca…",
  "This can take a moment for large libraries.": "Puede tardar un momento con bibliotecas grandes.",
  "{name} and the stored account data were deleted.": "Se eliminaron {name} y los datos de cuenta guardados.",
  "Largest photo by file size": "Foto de mayor tamaño",
  "Largest video by file size": "Vídeo de mayor tamaño",
  "largest known original file of this media type.": "mayor archivo original conocido de este tipo.",
  "Value": "Valor",
  "Y axis": "Eje Y",
  "Standard deviation": "Desviación estándar",
  "All photos": "Todas las fotos",
  "No dated photos with EXIF data are available for this value and filter.": "No hay fotos fechadas con datos EXIF para este valor y filtro.",
  "Line = arithmetic mean of photos with this EXIF value; gray band = ±1 population standard deviation. Missing values and undated photos are excluded.": "Línea = media aritmética de las fotos con este valor EXIF; banda gris = ±1 desviación estándar poblacional. No cuentan los valores ausentes ni las fotos sin fecha.",
  "Click a year to view matching photos from that period.": "Haz clic en un intervalo anual para ver las fotos correspondientes.",
  "Capture year {year}": "Año de captura {year}",
  "Device type": "Tipo de dispositivo",
  "Color landscape and portrait separately": "Distinguir horizontal y vertical por color",
  "Centered image format frames colored by frequency": "Formatos de imagen como marcos centrados y coloreados según su frecuencia",
  "Shared center; gray means no match for the filter. All {formats} stored formats are shown, covering {covered} of {photos} photos.": "Centro común; gris significa que no coincide con el filtro. Se ven los {formats} formatos guardados, que abarcan {covered} de {photos} fotos.",
  "Logarithmic color scale.": "Escala de color logarítmica.",
  "Linear color scale.": "Escala de color lineal.",
  "Most common image dimensions": "Dimensiones más frecuentes",
  "Hover or select a frame; click to view matching photos.": "Toca o selecciona un marco; haz clic para ver las fotos correspondientes.",
  "Square": "Cuadrado",
  "Your stored snapshot": "Tus datos guardados",
  "SQLite database": "Base de datos SQLite",
  "Calculating size once…": "Calculando el tamaño una vez…",
  "Size unavailable": "Tamaño no disponible",
  "Download SQLite": "Descargar SQLite",
  "Calculating size…": "Calculando tamaño…",
  "Selection": "Selección",
  "Manufacturer": "Fabricante",
  "All": "Todos",
  "Manufacturer · grouped": "Fabricantes · agrupados",
  "Manufacturer · individual": "Fabricantes · individuales",
  "Color mode": "Modo de color",
  "Count": "Cantidad",
  "Mobile device ↔ camera": "Móvil ↔ cámara",
  "Portrait ↔ landscape": "Vertical ↔ horizontal",
  "Photo ↔ video": "Foto ↔ vídeo",
  "Activity only": "Solo actividad",
  "Anniversaries": "Aniversarios",
  "Year overview": "Resumen anual",
  "Library over time": "Biblioteca a lo largo del tiempo",
  "On which day of the year do you capture media?": "¿En qué fecha del año capturas tus archivos?",
  "Capture calendar {year}": "Calendario de capturas {year}",
  "Your entire library by week": "Toda tu biblioteca por semanas",
  "all capture years": "todos los años de captura",
  "to": "hasta",
  "Empty · portrait · tie · landscape": "Vacío · Vertical · Empate · Horizontal",
  "Empty · photo · tie · video": "Vacío · Foto · Empate · Vídeo",
  "Empty · mobile device · tie · camera": "Vacío · Móvil · Empate · Cámara",
  "Unassigned": "Sin asignar",
  "Tie": "Empate",
  "Accent color = at least one capture": "Color de acento = al menos una captura",
  "{max} · {scale} · strongest color = maximum": "{max} · {scale} · color más intenso = valor máximo",
  "linear": "lineal",
  "logarithmic": "logarítmico",
  "Values summed over all capture years; February 29 remains a separate day.": "Valores sumados de todos los años de captura; el 29 de febrero mantiene su propia casilla.",
  "Monday to Sunday; exactly one cell per day.": "De lunes a domingo; una casilla por día.",
  "Rhythm": "Ritmo",
  "Hours of a typical week": "Horas de una semana típica",
  "All capture years in the selected period combined; each cell counts media captured in that weekday-hour.": "Se agrupan todos los años del período elegido; cada casilla cuenta los archivos de esa hora y día de la semana.",
  "{width} × {height} pixels: {count} photos in the selection": "{width} × {height} píxeles: {count} fotos en la selección",
  "{width} × {height} pixels · {count} in the selection": "{width} × {height} píxeles · {count} en la selección",
  "{selected} captures in the selection · {total} photos overall": "{selected} capturas seleccionadas · {total} fotos en total",
  "{value} by {axis}": "{value} por {axis}",
  "hour of day": "Hora del día",
  "{hour}:00": "{hour} h",
  "{bucket}: view {count} matching photos": "{bucket}: ver {count} fotos coincidentes",
  "Sync in progress": "Sincronización en curso",
  "Full sync": "Sincronización completa",
  "Fast incremental sync": "Sincronización incremental rápida",
  "Loading assets": "Cargando archivos",
  "Checking assets": "Comprobando archivos",
  "Loading changes": "Cargando cambios",
  "Checking assets without albums": "Comprobando archivos sin álbum",
  "Calculating statistics": "Calculando estadísticas",
  "Updating database": "Actualizando base de datos",
  "Calculating device assignments": "Calculando asignaciones de dispositivos localmente",
  "Calculating local statistics": "Calculando estadísticas localmente",
  "No changes": "Sin cambios",
  "Done": "Terminado",
  "Failed": "Error",
  "Metadata is missing for this distribution.": "Faltan metadatos para esta distribución.",
  "Individual values": "Valores individuales",
  "second": "Segundo",
  "seconds": "Segundos",
  "exposure stops": "Pasos de diafragma",
  "X axis": "Eje X",
  "Labels": "Etiquetas",
  "1/… seconds": "1/… segundos",
  "Decimal seconds": "Segundos decimales",
  "Typical range (up to 99%)": "Intervalo habitual (hasta el 99 %)",
  "Minimum captures per bar": "Capturas mínimas por barra",
  "Resolution": "Resolución",
  "No bar reaches the minimum frequency.": "Ninguna barra alcanza la frecuencia mínima.",
  "Median": "Mediana",
  "Mean": "Media",
  "Most frequent exact value": "Valor exacto más frecuente",
  "Smallest": "Menor",
  "Largest": "Mayor",
  "ISO value": "Valor ISO",
  "{count} captures with a value · The darker bar marks the most frequent displayed range; the accent line marks the most frequent exact value.": "{count} capturas con valor · La barra más oscura marca el intervalo visible más frecuente; la línea de acento, el valor exacto más frecuente.",
  "{bins} rare ranges with {assets} captures hidden.": "Se ocultan {bins} intervalos poco frecuentes con {assets} capturas.",
  "The most frequent exact value lies outside the visible ranges.": "El valor exacto más frecuente queda fuera del intervalo visible.",
  "Median, mean, and most frequent exact value still include all values.": "La mediana, la media y el valor exacto más frecuente siguen calculándose con todos los valores.",
  "{count} with known resolution": "{count} con resolución conocida",
  "Your selected range": "Tu selección",
  "1 bit = 1 second": "1 bit = 1 segundo",
  "Cost of all photo prints": "Precio de todas las copias",
  "Value of your memories": "Valor de tus recuerdos",
  "Mobile device (phone/tablet/iPod)": "Dispositivo móvil (teléfono/tableta/iPod)",
  "Other / unknown": "Otros / desconocidos",
  "Separate names": "Separar nombres",
  "Merge names": "Agrupar nombres",
  "No captures for this filter.": "No hay capturas para este filtro.",
  "Place": "Puesto",
  "Models": "Modelos",
  "EXIF names": "Nombres EXIF",
  "Which EXIF manufacturer names were merged?": "¿Qué nombres EXIF de fabricantes se han agrupado?",
  "No image dimensions are available for these years.": "No hay dimensiones de imagen para estos años.",
  "Show minimum and maximum": "Mostrar mínimo y máximo",
  "Photo resolution": "Resolución fotográfica",
  "Minimum": "Mínimo",
  "Maximum": "Máximo",
  "photos with dimensions": "Fotos con dimensiones",
  "Average": "Promedio",
  "By capture year, only photos with known dimensions. Minimum and maximum can be influenced by unusual image formats.": "Por año de captura, solo fotos con dimensiones conocidas. Un formato poco habitual puede influir mucho en el mínimo y el máximo.",
  "No original EXIF focal lengths available yet.": "Aún no hay distancias focales EXIF originales.",
  "Diagonal angle of view · schematic reach": "Ángulo diagonal de visión · alcance esquemático",
  "diagonal": "diagonal",
  "Top 5 by original EXIF focal length. To compare different cameras and calculate their actual angles of view, a 35 mm-equivalent focal length or sensor dimensions are needed. The plotted angles use a schematic full-frame reference; cone length is not subject distance. See Profile → Notes.": "Las cinco distancias focales EXIF originales más frecuentes. Para comparar cámaras y calcular sus ángulos de visión reales se necesita la distancia focal equivalente a 35 mm o el tamaño del sensor. Los ángulos mostrados son una referencia esquemática de formato completo; la longitud del cono no representa la distancia al motivo. Más información en Perfil → Notas.",
  "Inspired by the": "Inspirado en",
  "Correct device assignments": "Corregir asignación de dispositivos",
  "Immich Insights automatically classifies devices using EXIF manufacturer and model. Here you can rename combinations for your profile, assign a manufacturer, and classify them as camera, mobile device, or other. Original EXIF data remains unchanged.": "Immich Insights clasifica automáticamente los dispositivos según el fabricante y modelo EXIF. Aquí puedes renombrar combinaciones para tu perfil, asignarles un fabricante y clasificarlas como cámara, dispositivo móvil u otros. Los datos EXIF originales no cambian.",
  "Your devices appear here after the first sync.": "Tus dispositivos aparecerán aquí tras la primera sincronización.",
  "Search devices": "Buscar dispositivo",
  "Manufacturer or model": "Fabricante o modelo",
  "Corrected": "Corregido",
  "Automatic": "Automático",
  " · corrected": " · corregido",
  "No matching devices.": "No hay dispositivos coincidentes.",
  "Current assignment": "Asignación actual",
  "Device category": "Categoría de dispositivo",
  "Save correction": "Guardar corrección",
  "Reset": "Restablecer",
  "Choose a device on the left.": "Selecciona un dispositivo a la izquierda.",
  "Saved. Statistics are recalculated locally without a new Immich scan.": "Guardado. Las estadísticas se recalcularán localmente, sin volver a analizar Immich.",
  "Correction removed. Automatic classification is restored locally.": "Corrección eliminada. Se restableció la asignación automática local.",
  "Photo days & rhythm": "Días de fotos y ritmo",
  "Your activity in numbers": "Tu actividad en cifras",
  "Avg. photos per photo day": "Fotos medias por día fotográfico",
  "Avg. streak length": "Duración media de la racha",
  "Avg. break between photo days": "Pausa media entre días fotográficos",
  "Avg. activity cycle": "Ciclo de actividad medio",
  "Avg. photos/day in streaks": "Fotos medias por día de racha",
  "Maximum on a streak day": "Máximo en un día de racha",
  "Streak vs. normal photo day": "Racha frente a día fotográfico normal",
  "Photo days in ≥3-day streaks": "Días fotográficos en rachas de ≥3 días",
  "A photo day has at least one photo. A streak contains at least two consecutive photo days; a break counts only complete photo-free days between activity phases. A cycle includes an activity phase, even a single day, followed by its break.": "Día fotográfico = al menos una foto. Una racha consta de al menos dos días fotográficos consecutivos; una pausa cuenta solo días completos sin fotos entre fases activas. Un ciclo incluye una fase activa, incluso de un solo día, y su pausa posterior.",
  "Distributions": "Distribuciones",
  "How long do streaks and breaks last?": "¿Cuánto duran las rachas y las pausas?",
  "Streak lengths": "Duración de las rachas",
  "Streak days": "Días de racha",
  "Break days": "Días de pausa",
  "No completed multi-day streaks yet.": "Aún no hay rachas completas de varios días.",
  "No completed breaks yet.": "Aún no hay pausas completas.",
  "Number of phases": "Número de fases",
  "After a streak": "Después de una racha",
  "Intensity and following break": "Intensidad y pausa posterior",
  "Do more photos per streak day lead to a longer break?": "¿Más fotos por día de racha implican una pausa posterior más larga?",
  "Completed streaks with a following break are needed for comparison.": "Faltan rachas completas seguidas de una pausa para la comparación.",
  "Photos/day in a streak → avg. break days; streaks of at least two days": "Fotos por día de racha → días medios de pausa; solo rachas de al menos dos días",
  "Pearson correlation": "Correlación de Pearson",
  "−1: more intense streaks, shorter breaks · 0: no linear relation · +1: longer breaks. Requires at least three evaluable streak-break pairs.": "−1: rachas más intensas y pausas más cortas · 0: sin relación lineal · +1: pausas más largas. Solo con al menos tres pares de racha y pausa evaluables.",
  "Seven indices": "Siete índices",
  "How do you photograph?": "¿Cómo fotografías?",
  "Indices describe patterns, not photographic quality. When there are too few photo days or breaks, “—” appears instead of an invented value.": "Los índices describen patrones, no calidad fotográfica. Si hay muy pocos días fotográficos o pausas, se muestra «—» en vez de inventar un valor.",
  "Over the years": "A lo largo de los años",
  "How does your photo profile change?": "¿Cómo cambia tu perfil fotográfico?",
  "Regularity": "Regularidad",
  "Streaks ↔ breaks ↔ stability": "Rachas ↔ pausas ↔ estabilidad",
  "Avg. streak": "Racha media",
  "Avg. break": "Pausa media",
  "Stability index": "Índice de estabilidad",
  "Stability compares average multi-day streak length with average break length. A high value does not automatically mean more or better photos.": "La estabilidad compara la duración media de las rachas de varios días con la pausa media. Un valor alto no implica necesariamente más fotos ni fotos mejores.",
  "The annual comparison appears once at least two capture years are available.": "La comparación anual aparecerá cuando haya al menos dos años de capturas.",
  "Annual trend of selected photo profile indices": "Evolución anual de los índices fotográficos elegidos",
  "Calculated separately for each calendar year. Streaks and breaks are split at year boundaries.": "Se calcula por año natural. Las rachas y las pausas se separan al cambiar de año.",
  "Focus index": "Índice de concentración",
  "Volatility index": "Índice de volatilidad",
  "Habit strength index": "Índice de hábitos",
  "Rhythm regularity index": "Índice de regularidad del ritmo",
  "Momentum index": "Índice de impulso",
  "Burnout index": "Índice de agotamiento",
  "Share of all photos captured on the most active rounded-up 10% of photo days.": "Proporción de todas las fotos tomadas en el 10 % de días fotográficos más activos, redondeado hacia arriba.",
  "Variation in photos per photo day: 100 × coefficient of variation / (1 + coefficient of variation).": "Variación de fotos por día fotográfico: 100 × coeficiente de variación / (1 + coeficiente de variación).",
  "Share of photo days belonging to a streak of at least three days.": "Proporción de días fotográficos que forman parte de una racha de al menos tres días.",
  "100 / (1 + coefficient of variation of intervals between photo days). At least three photo days required.": "100 / (1 + coeficiente de variación de los intervalos entre días fotográficos). Se necesitan al menos tres días.",
  "Average photos on first streak days / (average first days + average later streak days) × 100. A score of 50 means equal intensity.": "Fotos medias del primer día de racha / (media de primeros días + media de días siguientes) × 100. 50 significa igual intensidad.",
  "Average break after ≥3-day streaks / (that break + overall average break) × 100. A score of 50 means equally long breaks.": "Pausa media tras rachas de ≥3 días / (esa pausa + pausa media general) × 100. 50 significa pausas de igual duración.",
  "Average streak length / (average streak length + average break) × 100.": "Duración media de racha / (duración media de racha + pausa media) × 100.",
  "Between two poles": "Entre dos polos",
  "The marker shows your tendency. The exact method is listed under “Calculation”. This is not a rating.": "El punto muestra tu tendencia. El cálculo exacto figura en «Cálculo». No es una valoración.",
  "Your photo personality appears once enough matching metadata is available.": "Tu personalidad fotográfica aparecerá cuando haya suficientes metadatos.",
  "Labeled radar chart of six tendencies": "Gráfico radial de las seis tendencias",
  "Undetermined": "Indeterminado",
  "undetermined": "indeterminado",
  "Leaning toward {pole}": "Más bien {pole}",
  "Evenly balanced": "Equilibrado",
  "{percent}% toward {pole}": "{percent} % hacia {pole}",
  "{eligible} of {total} {kind} eligible": "{eligible} de {total} {kind} evaluables",
  " · {count} excluded": " · {count} excluidos",
  "Calculation": "Cálculo",
  "Connections in the radar chart are missing when individual tendencies cannot be determined.": "En el gráfico radial faltan conexiones cuando una tendencia no puede determinarse.",
  "Media": "Archivos",
  "Daylight": "Luz diurna",
  "Night": "Noche",
  "ISO / light": "ISO / luz",
  "Bright light": "Luz brillante",
  "Low light": "Poca luz",
  "Capture frequency": "Frecuencia de captura",
  "Frequency": "Frecuencia",
  "Single shot": "Foto aislada",
  "Burst mode": "Ráfaga",
  "Orientation": "Orientación",
  "Capture device": "Dispositivo de captura",
  "Media mix": "Mezcla de medios",
  "08:00–18:00: 0 · 06:00–08:00 & 18:00–22:00: 0.5 · 22:00–06:00: 1": "08–18 h: 0 · 06–08 y 18–22 h: 0,5 · 22–06 h: 1",
  "Up to ISO 400: 0 · 800–1600: 0.5 · ISO 3200+: 1; linear in between.": "Hasta ISO 400: 0 · 800–1600: 0,5 · desde 3200: 1; interpolación lineal.",
  "Time since the previous photo: up to 5 s = 1 · 10 min or more = 0; linear in between.": "Intervalo desde la foto anterior: hasta 5 s = 1 · desde 10 min = 0; interpolación lineal.",
  "Landscape: 0 · square: 0.5 · portrait: 1.": "Horizontal: 0 · cuadrado: 0,5 · vertical: 1.",
  "Camera: 0 · phone/tablet/iPod: 1 · other excluded.": "Cámara: 0 · teléfono/tableta/iPod: 1 · se excluyen otros dispositivos.",
  "Photos: 0 · videos: 1. The score is the video share of all photos and videos.": "Fotos: 0 · vídeos: 1. El valor es la proporción de vídeos entre todas las fotos y vídeos.",
  "Film architect": "Arquitecto de películas",
  "You like telling stories in moving images.": "Te gusta contar historias con imágenes en movimiento.",
  "Moment keeper": "Guardián de momentos",
  "One moment can carry your stories.": "Un solo instante cuenta tus historias.",
  "Night chronicler": "Cronista nocturno",
  "Your subjects begin where daylight ends.": "Tus motivos aparecen cuando termina la luz del día.",
  "Light collector": "Coleccionista de luz",
  "You make use of daylight clarity.": "Aprovechas la claridad del día.",
  "Low-light seeker": "Explorador de la penumbra",
  "Challenging light does not stop you.": "La luz difícil tampoco te detiene.",
  "Moment hunter": "Cazador de instantes",
  "You capture fast action in bursts.": "Capturas movimientos rápidos en ráfagas.",
  "Portrait storyteller": "Narrador vertical",
  "You often frame scenes vertically.": "Sueles ver escenas en vertical.",
  "Wide-frame thinker": "Mirada panorámica",
  "You give your subjects room across the frame.": "Das espacio a tus motivos en horizontal.",
  "Pocket reporter": "Reportero de bolsillo",
  "Your camera is always with you.": "Siempre llevas una cámara contigo.",
  "Camera artist": "Artista de cámara",
  "You often reach for a dedicated camera.": "Te gusta usar una cámara dedicada.",
  "No dated photos or videos are available for an annual trend.": "No hay fotos o vídeos fechados para mostrar una evolución anual.",
  "Choose a tendency. Each point represents a capture year; gaps indicate years without matching captures.": "Elige una tendencia. Cada punto representa un año de captura; los huecos indican años sin capturas correspondientes.",
  "Choose one or more tendencies. Each point represents a capture year; gaps indicate years without matching captures.": "Elige una o varias tendencias. Cada punto representa un año de captura; los huecos son años sin capturas válidas.",
  "Annual trend of selected tendencies": "Evolución anual de las tendencias seleccionadas",
  "Annual trend": "Evolución anual",
  "Annual tendency between {low} and {high}": "Tendencia anual entre {low} y {high}",
  "Capture year {year}: {tendency}": "Año de captura {year}: {tendency}",
  "The middle means balanced. The right pole is at the top, the left at the bottom. Capture frequency only compares photos within the same year.": "El centro representa un equilibrio. Arriba está el polo derecho y abajo el izquierdo. En la frecuencia de captura solo cuenta el intervalo respecto a fotos del mismo año.",
  "The middle means balanced. Each metric’s second pole is at the top and first pole at the bottom. Capture frequency only compares photos within the same year.": "El centro indica equilibrio. El segundo polo está arriba y el primero abajo. La frecuencia solo compara fotos del mismo año.",
  "Remainder": "Resto",
  "Cumulative captures": "Capturas acumuladas",
  "New captures in year": "Nuevas capturas del año",
  "Top 5 + other": "Los 5 primeros + resto",
  "Group": "Grupo",
  "Cameras": "Cámaras",
  "Mobile devices": "Dispositivos móviles",
  "Top order": "Arriba",
  "Largest contribution": "Mayor contribución",
  "Newest devices": "Dispositivos más recientes",
  "No matching captures available.": "No hay capturas coincidentes.",
  "Streamgraph of the five most frequent devices or manufacturers": "Gráfico de flujo de los cinco dispositivos o fabricantes más frecuentes",
  "Through {year}": "Hasta {year}",
  "In {year}": "En {year}",
  "The top five depend on the selected metric and device type. Vertical order is recalculated each year, so ribbons cross when rankings change. “Other” groups all remaining devices.": "Los cinco primeros se basan en la métrica y el tipo de dispositivo elegidos. El orden vertical se recalcula cada año, por lo que las áreas se cruzan al cambiar de posición. «Resto» agrupa los demás dispositivos.",
  "No capture years available yet.": "Aún no hay años de captura.",
  "Percentage change in captures year over year": "Variación porcentual de capturas respecto al año anterior",
  "Captures by capture year": "Capturas por año de captura",
  "Captures by year of capture": "Capturas por año",
  "no previous-year value": "Sin dato del año anterior",
  "Captures are grouped by capture date, not import date. Hover also shows year-over-year change; the current year is incomplete.": "Capturas según la fecha de toma, no la de importación. Al pasar el cursor se muestra también el cambio respecto al año anterior; el año actual aún está incompleto.",
  "Loading Immich Insights…": "Cargando Immich Insights…",
  "Accept invitation.": "Aceptar invitación.",
  "Welcome. Set up your account.": "Te damos la bienvenida. Configura tu cuenta.",
  "Welcome back.": "Bienvenido de nuevo.",
  "Set your own password. Then you can add your Immich API key.": "Elige una contraseña. Después podrás añadir tu clave API de Immich.",
  "The first account automatically becomes admin and can invite others.": "La primera cuenta será administradora y podrá invitar a otras personas.",
  "Sign in to see only your own library.": "Inicia sesión para ver únicamente tu biblioteca.",
  "Name": "Nombre",
  "Email": "Correo electrónico",
  "Password": "Contraseña",
  "Activate account": "Activar cuenta",
  "Create admin account": "Crear cuenta de administración",
  "Sign in": "Iniciar sesión",
  "Use at least 12 characters for your password.": "La contraseña debe tener al menos 12 caracteres.",
  "Profile saved.": "Perfil guardado.",
  "Immich connection saved. Test it with the button now.": "Conexión de Immich guardada. Compruébala con el botón.",
  "Password changed.": "Contraseña cambiada.",
  "New invitation link created for {name}.": "Se creó un nuevo enlace de invitación para {name}.",
  "{format} report": "Informe {format}",
  "Download {format}": "Descargar {format}",
  "{count} matching captures · {shown} shown": "{count} capturas coincidentes · {shown} mostradas",
  "Original EXIF manufacturer names": "Nombres originales de fabricante EXIF",
  "Included models": "Modelos incluidos",
  "Exposure": "Exposición",
  "Your exposure triangle": "Tu triángulo de exposición",
  "Each dot is a photo with complete ISO, shutter, and aperture data. The closer it is to a corner, the more that parameter deviates from your usual value relative to the other two. In the center, all three influences are similar. This does not assess image quality or correct exposure.": "Cada punto representa una foto con ISO, tiempo y abertura completos. Cuanto más cerca está de un vértice, más se aparta ese parámetro de tu valor habitual en comparación con los otros dos. En el centro, las tres influencias son similares; no indica calidad ni exposición correcta.",
  "All years": "Todos los años",
  "Scale clipping": "Recorte de escala",
  "Color": "Color",
  "Corner proximity": "Cercanía al vértice",
  "Show axis values": "Mostrar valores de los ejes",
  "Spread": "Dispersión",
  "Exposure triangle with {count} individual photo dots": "Triángulo de exposición con {count} puntos de fotos",
  "High ISO": "ISO alto",
  "Long shutter time": "Exposición larga",
  "Wide aperture": "Diafragma abierto",
  "center": "Centro",
  "high corner approx.": "vértice alto aprox.",
  "Time": "Tiempo",
  "long corner approx.": "vértice largo aprox.",
  "wide corner approx.": "vértice abierto aprox.",
  "No photos with complete exposure data match this selection.": "No hay fotos con datos completos de exposición para esta selección.",
  "High ISO value": "ISO alto",
  "More signal amplification helps in low light but can increase noise.": "Amplificar la señal ayuda con poca luz, pero puede aumentar el ruido de la imagen.",
  "The sensor gathers light for longer; motion can become blur or camera shake.": "El sensor recibe luz durante más tiempo; el movimiento puede producir desenfoque o trepidación.",
  "A smaller f-number means a wider opening: more light and shallower depth of field, often with a blurrier background.": "Un número f menor significa una abertura mayor: entra más luz y disminuye la profundidad de campo, con un fondo a menudo más desenfocado.",
  "{count} dots shown": "{count} puntos mostrados",
  "{count} photos without a complete ISO/shutter/aperture trio": "{count} fotos sin el trío completo de ISO, tiempo y diafragma",
  "Clipping limits outliers on the scale; no photo is hidden.": "El recorte limita los valores atípicos en la escala; no oculta ninguna foto.",
  "ISO-dominant": "Predomina ISO",
  "Shutter-dominant": "Predomina el tiempo",
  "Aperture-dominant": "Predomina el diafragma",
  "How to read this: start with a corner. A dot near “High ISO” has an unusually high ISO relative to its other two settings among your selected photos. Between corners, both settings stand out; near the center, all three are similar. ISO and shutter time use log₂ stops; aperture light effect uses −2 log₂(f-number). Each parameter is centered on its median; 95/99% clipping only limits extreme scale values. The three relative values are then blended into a triangle position. This chart does not show absolute brightness, correct exposure, or quality. Depth-of-field comparison additionally depends on sensor size, angle of view, focus distance, and output size; the EXIF f-number is not converted. Hover a dot for its exact EXIF values.": "Cómo leerlo: elige primero un vértice. Un punto cerca de «ISO alto» tiene un ISO inusualmente alto frente a los otros dos parámetros para las fotos seleccionadas. Entre dos vértices destacan ambos parámetros; en el centro tienen una influencia similar. ISO y tiempo se expresan en pasos log₂, y el efecto luminoso de la abertura como −2 log₂(número f). La mediana centra cada parámetro; los percentiles 95/99 solo limitan valores extremos de la escala. Después se combinan los tres valores relativos para situar el punto. El gráfico no muestra brillo absoluto, exposición correcta ni calidad. Para comparar profundidad de campo también importan tamaño del sensor, ángulo de visión, distancia de enfoque y tamaño de salida; aquí no se convierte el número f real del EXIF. Toca un punto para ver sus valores EXIF.",
  "Area = number of {metric}": "Área = número de {metric}",
  "Metric": "Métrica",
  "No matching devices available.": "No hay dispositivos coincidentes.",
  "Treemap of manufacturers and devices by {metric}": "Mapa de áreas de fabricantes y dispositivos según {metric}",
  "Each large area is a manufacturer; inner areas are devices. Click an area to view its assets.": "Cada área grande representa un fabricante; las subáreas son dispositivos. Haz clic para ver los archivos correspondientes.",
  "No image dimensions available.": "No hay dimensiones disponibles.",
  "Confirm member deletion": "Confirmar eliminación del miembro",
  "About {count} A4 pages": "Unas {count} hojas A4",
  "About {count} parking spaces (2.5 × 5 m)": "Unas {count} plazas de aparcamiento de 2,5 × 5 m",
  "About {count} doubles tennis courts": "Unas {count} pistas de tenis dobles",
  "h": "h",
  "min": "min",
  "s": "s",
  "First photo with {device}": "Primera foto con {device}",
  "Last photo with {device}": "Última foto con {device}",
  "{count}th {kind}": "{count}.º {kind}",
  "asset": "Archivo",
  "geotagged photo": "Foto con ubicación",
  "detected face": "Rostro detectado",
  "First photo": "Primera foto",
  "First geotagged photo": "Primera foto con ubicación",
  "First photo with a person": "Primera foto con una persona",
  "First favorite": "Primer favorito",
  "First video": "Primer vídeo",
  "Shortest video": "Vídeo más corto",
  "Longest video": "Vídeo más largo",
  "Lowest ISO": "ISO más bajo",
  "Highest ISO": "ISO más alto",
  "Shortest shutter time": "Exposición más breve",
  "Longest shutter time": "Exposición más larga",
  "Widest aperture": "Abertura más amplia",
  "Smallest aperture opening": "Abertura más pequeña",
  "Busiest photo day": "Día con más fotos",
  "Busiest video day": "Día con más vídeos",
  "Start of longest break": "Inicio de la pausa más larga",
  "End of longest break": "Fin de la pausa más larga",
  "Start of longest daily streak": "Inicio de la racha diaria más larga",
  "End of longest daily streak": "Fin de la racha diaria más larga",
  "{size} MB · largest known original file of this media type.": "{size} MB · mayor archivo original conocido de este tipo.",
  "{seconds} seconds · standalone video with known duration; Live Photo companion videos excluded.": "{seconds} segundos · vídeo independiente con duración conocida; se excluyen los vídeos asociados a Live Photos.",
  "Earliest dated capture in your library.": "La captura fechada más antigua de tu biblioteca.",
  "Latest dated capture in your library.": "La captura fechada más reciente de tu biblioteca.",
  "First dated medium of this type.": "Primer archivo fechado de este tipo.",
  "First dated photo with this device.": "Primera foto fechada con este dispositivo.",
  "Latest dated photo with this device.": "Foto fechada más reciente con este dispositivo.",
  "{value} · only photo with this extreme value.": "{value} · única foto con este valor extremo.",
  "{count} {kind} on this capture day.": "{count} {kind} en este día de captura.",
  "Followed by {days} calendar days without a dated capture.": "Después hubo {days} días naturales sin capturas fechadas.",
  "First capture after {days} calendar days without a dated capture.": "Primera captura tras {days} días naturales sin capturas fechadas.",
  "Captures were made on {days} consecutive days.": "Hubo capturas durante {days} días consecutivos.",
  "Last day of a {days}-day capture streak.": "Último día de una racha de {days} días de captura.",
  "Counted chronologically by capture time; undated media are excluded. ": "Contado cronológicamente por fecha de captura; se excluyen los archivos sin fecha. ",
  "Counted chronologically by capture time; undated media are excluded. Multiple faces in one photo count separately; they are not distinct people.": "Contado cronológicamente por fecha de captura; se excluyen los archivos sin fecha. Varios rostros en una foto cuentan por separado, no necesariamente como personas diferentes.",
  "GPS altitude": "Altitud GPS",
  "the selected asset only": "exactamente el archivo seleccionado",
  "captured with device “{name}”": "capturado con el dispositivo «{name}»",
  "captured with devices of EXIF manufacturer “{name}”": "capturado con dispositivos del fabricante EXIF «{name}»",
  "captured with devices of grouped manufacturer “{name}”": "capturado con dispositivos del fabricante agrupado «{name}»",
  "{lower} through {upper}": "de {lower} a {upper}, inclusive",
  "{lower} to under {upper}": "de {lower} a menos de {upper}",
  "with {field} in range {interval} {unit}": "con {field} en el intervalo {interval} {unit}",
  "in portrait orientation": "en vertical",
  "in landscape orientation": "en horizontal",
  "with square or undetermined orientation": "con formato cuadrado o indeterminado",
  "with dimensions {width} × {height} pixels": "con dimensiones de {width} × {height} píxeles",
  "captured on {date}": "capturado el {date}",
  "captured on {date} (all years)": "capturado un {date} (todos los años)",
  "captured from {start} through {end} (inclusive)": "capturado del {start} al {end}, inclusive",
  "captured on {weekday} between {hour}": "capturado un {weekday} entre las {hour}",
  "captured in {month} (all years)": "capturado en el mes {month} (todos los años)",
  "captured on a {weekday} (all years)": "capturado un {weekday} (todos los años)",
  "captured between {hour} (all days)": "capturado entre las {hour} (todos los días)",
  "captured in {year}": "capturado en {year}",
  "device “{name}”": "dispositivo «{name}»",
  "with camera “{name}”": "con la cámara «{name}»",
  "EXIF manufacturer “{name}”": "fabricante EXIF «{name}»",
  "manufacturer “{name}”": "fabricante «{name}»",
  "category {category}": "categoría {category}",
  "favorites only": "solo favoritos",
  "with location data": "con datos de ubicación",
  "with detected people": "con una persona detectada",
  "with a usable value for {field}": "con un valor utilizable para {field}",
  "square/unknown": "cuadrado/indeterminado",
  " in {year}": " en {year}",
  " from {start} through {end}": " del {start} al {end}",
  "Your {metric}{scope}: {detail}. Capture times follow the local date in Immich.": "Tus {metric}{scope}: {detail}. Las fechas de captura corresponden a la fecha local de Immich.",
  "Request failed.": "La solicitud falló.",
  "Device assignments could not be recalculated. The previous snapshot remains available.": "No se pudo recalcular la asignación de dispositivos. Se conservan los últimos datos.",
  "Sync failed. Check the connection and API permissions. The last complete snapshot remains available.": "Falló la sincronización. Comprueba la conexión y los permisos API. Se conserva la última instantánea completa.",
  "Snapshot from an older version. Please select “Refresh now”.": "Los datos son de una versión anterior. Pulsa «Actualizar ahora».",
  "Sync interrupted by a restart. Please refresh again.": "La sincronización se interrumpió por un reinicio. Actualiza de nuevo.",
  "No snapshot yet. Please start a refresh.": "Aún no hay datos. Inicia una actualización.",
  "Invalid device or date-range filter.": "Filtro de dispositivo o período no válido.",
  "Choose a specific EXIF device.": "Selecciona un dispositivo EXIF concreto.",
  "Device name and manufacturer cannot both be empty.": "El nombre del dispositivo y el fabricante no pueden estar vacíos.",
  "Enter at least one correction.": "Introduce al menos una corrección.",
  "Please wait until the current sync finishes.": "Espera a que termine la sincronización actual.",
  "Snapshot changed during export. Please try again.": "Los datos cambiaron durante la exportación. Inténtalo de nuevo.",
  "No statistics available yet.": "Aún no hay estadísticas disponibles.",
  "Unknown export format.": "Formato de exportación desconocido.",
  "Setup is already complete.": "La configuración ya se completó.",
  "Enter a name.": "Introduce un nombre.",
  "Setup has already been completed.": "La configuración ya se ha completado.",
  "Email or password is incorrect.": "El correo o la contraseña son incorrectos.",
  "This invitation link is invalid or expired.": "Este enlace de invitación no es válido o ha caducado.",
  "Only the admin can list users.": "Solo la cuenta administradora puede listar usuarios.",
  "This email address is already in use.": "Esta dirección de correo ya está en uso.",
  "Pending invitation not found.": "No se encontró la invitación pendiente.",
  "Type delete to confirm.": "Para confirmar, escribe delete.",
  "Member not found.": "No se encontró al miembro.",
  "An admin account cannot be deleted here.": "Aquí no se puede eliminar una cuenta administradora.",
  "Sync is still running. Please try again afterward.": "La sincronización sigue en curso. Vuelve a intentarlo después.",
  "Name or profile icon is invalid.": "El nombre o el icono del perfil no son válidos.",
  "Current password is incorrect.": "La contraseña actual es incorrecta.",
  "First save your Immich URL and API key in your profile.": "Guarda primero la URL de Immich y tu clave API en el perfil.",
  "The stored API key cannot be decrypted.": "No se puede descifrar la clave API guardada.",
  "Immich is unreachable from the backend. Check the URL and Docker network.": "El servidor no puede acceder a Immich. Comprueba la URL y la red Docker.",
  "Immich could not be queried. Check the connection and try again.": "No se pudo consultar Immich. Comprueba la conexión e inténtalo de nuevo.",
  "Invalid year selection.": "Selección de año no válida.",
  "Enter a valid date range.": "Introduce un período válido.",
  "Image not found.": "No se encontró la imagen.",
  "No Immich profile image available.": "No hay foto de perfil de Immich disponible.",
  "Please sign in.": "Inicia sesión.",
  "Please sign in again.": "Vuelve a iniciar sesión.",
  "Invalid form protection. Reload the page.": "Protección del formulario no válida. Recarga la página.",
  "Only the admin can invite users.": "Solo la cuenta administradora puede invitar usuarios.",
  "Asset ID is missing.": "Falta el ID del archivo.",
  "Device or manufacturer is missing.": "Falta el dispositivo o fabricante.",
  "Distribution range is missing.": "Falta el intervalo de distribución.",
  "Invalid value range.": "Intervalo de valores no válido.",
  "Capture date is missing.": "Falta la fecha de captura.",
  "Invalid capture date.": "Fecha de captura no válida.",
  "Invalid anniversary date.": "Aniversario no válido.",
  "Invalid calendar week.": "Semana natural no válida.",
  "Time filter is incomplete.": "Filtro temporal incompleto.",
  "Invalid device category.": "Categoría de dispositivo no válida.",
  "Image orientation is missing.": "Falta la orientación de la imagen.",
  "Image dimensions are missing.": "Faltan las dimensiones de la imagen.",
  "Invalid date-range restriction.": "Restricción del período no válida.",
  "Number format": "Formato numérico",
  "Focal length": "Distancia focal",
  "This changes separators in statistics and charts, not the stored values.": "Esta opción cambia los separadores en estadísticas y gráficos, no los valores guardados.",
  "Thousands and decimal separators": "Separadores de miles y decimales",
  "Media marked as favorites": "Archivos marcados como favoritos",
  "Original sizes of all photos, when complete": "Tamaños originales de todas las fotos, si están completos",
  "Original sizes of all videos, when complete": "Tamaños originales de todos los vídeos, si están completos",
  "Only when all original sizes are known": "Solo si se conocen todos los tamaños originales",
  "Only when all photo sizes are known": "Solo si se conocen todos los tamaños de fotos",
  "Only when all video sizes are known": "Solo si se conocen todos los tamaños de vídeos",
  "Photos with at least one detected face": "Fotos con al menos un rostro detectado",
  "Unique person IDs in the snapshot": "Identificadores únicos de personas en los datos",
  "Only photos with detected faces": "Solo fotos con rostros detectados",
  "Including photos without detected faces": "Incluye fotos sin rostros detectados",
  "Assets with latitude and longitude": "Archivos con latitud y longitud",
  "No country information available": "No hay información de países",
  "No continents can be determined": "No se pueden determinar continentes",
  "Automatic for language": "Automático según el idioma",
  "Preview": "Vista previa",
  "Notes": "Notas",
  "About this project & what is next": "Sobre el proyecto y próximos pasos",
  "Immich Insights began with a simple idea: make full use of the control you have over your own photos and videos. It turns library data into new perspectives on your memories, especially for a personal year-in-review.": "Immich Insights nació de una idea sencilla: aprovechar el control que tienes sobre tus propias fotos y vídeos. Los datos de tu biblioteca ofrecen nuevas perspectivas sobre tus recuerdos, especialmente para crear un resumen personal del año.",
  "Understanding metadata": "Entender los metadatos",
  "EXIF is not always consistent: manufacturers and devices store some details differently or omit them. Immich exposes selected, processed EXIF fields through its asset API, but not a general raw EXIF dump.": "EXIF no siempre es uniforme: los fabricantes y dispositivos guardan algunos datos de forma distinta o los omiten. La API de archivos de Immich ofrece campos EXIF seleccionados y procesados, pero no una exportación general de EXIF sin procesar.",
  "An optional raw-metadata import or additional Immich API fields could eventually show flash usage, camera directions as a compass rose, and GPS altitudes as a hypsometric curve. Some original metadata also includes a 35 mm-equivalent focal length or camera details needed to derive one. Where available, it could make focal lengths and actual angles of view more comparable across cameras. We do not guess when reliable data is unavailable.": "Una futura importación opcional de metadatos originales o más campos de la API de Immich permitirían mostrar el uso del flash, las direcciones como rosa de los vientos y las altitudes GPS como curva hipsométrica. Algunos metadatos originales también incluyen la distancia focal equivalente a 35 mm o datos de la cámara necesarios para calcularla. Cuando estén disponibles, permitirán comparar mejor las distancias focales y los ángulos de visión reales entre cámaras. No inventamos valores si faltan datos fiables.",
  "Planned ideas": "Ideas previstas",
  "Filterable maps could highlight special captures such as your southernmost photo. Small Immich thumbnails could later reveal your personal color palette without permanently copying original files.": "Los mapas filtrables podrían destacar fotos especiales, como la más meridional. Las miniaturas pequeñas de Immich podrían revelar tu paleta de colores personal sin copiar permanentemente los originales.",
  "A simple photo-book integration is another idea: a page or two could enrich your year-in-review with selected statistics.": "Otra idea es una integración sencilla con álbumes de fotos: una o dos páginas podrían complementar tu resumen anual con estadísticas seleccionadas.",
  "We are currently improving performance and working on more useful, better-looking downloads. The project will keep evolving; ideas and bug reports are welcome.": "Estamos mejorando el rendimiento y preparando descargas más útiles y mejor presentadas. El proyecto seguirá evolucionando; agradecemos las ideas y los informes de errores.",
  "Made with AI, shaped by people": "Creado con IA, guiado por personas",
  "AI tools helped build parts of Immich Insights. The concept, product decisions, verification, and ongoing care still require substantial human work. It is not meant to replace Immich as a full-featured media viewer; it shows what your library data can reveal from another perspective.": "Las herramientas de IA ayudaron a desarrollar partes de Immich Insights. El concepto, las decisiones de producto, la verificación y el mantenimiento siguen requiriendo mucho trabajo humano. No pretende sustituir a Immich como visor multimedia completo, sino mostrar lo que los datos de tu biblioteca pueden revelar desde otra perspectiva.",
  "Run it safely": "Uso seguro",
  "This instance contains private library and location data. Prefer running it only on your home network; do not expose it directly to the internet. If remote access is necessary, use at least HTTPS and strong access controls.": "Esta instancia contiene datos privados de la biblioteca y ubicaciones. Es preferible usarla solo en tu red doméstica y no exponerla directamente a Internet. Si necesitas acceso remoto, usa al menos HTTPS y controles de acceso sólidos.",
  "Tips for meaningful statistics": "Consejos para estadísticas útiles",
  "Accurate capture dates matter most: incorrect timestamps distort years, streaks, and maps. Keep screenshots separate from memory photos where possible. In large libraries, favorites often help more than hasty deletion.": "Las fechas de captura correctas son fundamentales: las marcas de tiempo erróneas distorsionan los años, las rachas y los mapas. Separa las capturas de pantalla de las fotos de recuerdos cuando sea posible. En bibliotecas grandes, los favoritos suelen ayudar más que borrar deprisa.",
  "Support on Buy Me a Coffee": "Apoyar en Buy Me a Coffee",
  "Open an issue or share feedback": "Abrir una incidencia o enviar comentarios",
  "Found a bug or have an idea? Open a GitHub issue. If you would also like to support further development, a coffee is appreciated but never required.": "¿Has encontrado un error o tienes una idea? Abre una incidencia en GitHub. Si además quieres apoyar el desarrollo, se agradece un café, pero nunca es obligatorio.",
  "Format": "Formato",
};
